// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

mod classes;
mod enums;

pub use classes::*;
pub use enums::*;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: ::std::sync::Arc<::baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: ::std::sync::Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &::baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================


    /// Access the `DiscoveryRerankCandidate` class builder.
    pub fn DiscoveryRerankCandidate(&self) -> DiscoveryRerankCandidateClassBuilder {
        DiscoveryRerankCandidateClassBuilder::new(
            self.inner.get_class("DiscoveryRerankCandidate")
                .expect("class DiscoveryRerankCandidate is defined in schema")
        )
    }


    /// Access the `DomainCapability` class builder.
    pub fn DomainCapability(&self) -> DomainCapabilityClassBuilder {
        DomainCapabilityClassBuilder::new(
            self.inner.get_class("DomainCapability")
                .expect("class DomainCapability is defined in schema")
        )
    }


    /// Access the `DomainEntity` class builder.
    pub fn DomainEntity(&self) -> DomainEntityClassBuilder {
        DomainEntityClassBuilder::new(
            self.inner.get_class("DomainEntity")
                .expect("class DomainEntity is defined in schema")
        )
    }


    /// Access the `DomainField` class builder.
    pub fn DomainField(&self) -> DomainFieldClassBuilder {
        DomainFieldClassBuilder::new(
            self.inner.get_class("DomainField")
                .expect("class DomainField is defined in schema")
        )
    }


    /// Access the `DomainModel` class builder.
    pub fn DomainModel(&self) -> DomainModelClassBuilder {
        DomainModelClassBuilder::new(
            self.inner.get_class("DomainModel")
                .expect("class DomainModel is defined in schema")
        )
    }


    /// Access the `DomainModelValidation` class builder.
    pub fn DomainModelValidation(&self) -> DomainModelValidationClassBuilder {
        DomainModelValidationClassBuilder::new(
            self.inner.get_class("DomainModelValidation")
                .expect("class DomainModelValidation is defined in schema")
        )
    }


    /// Access the `DomainParameter` class builder.
    pub fn DomainParameter(&self) -> DomainParameterClassBuilder {
        DomainParameterClassBuilder::new(
            self.inner.get_class("DomainParameter")
                .expect("class DomainParameter is defined in schema")
        )
    }


    /// Access the `DomainRelation` class builder.
    pub fn DomainRelation(&self) -> DomainRelationClassBuilder {
        DomainRelationClassBuilder::new(
            self.inner.get_class("DomainRelation")
                .expect("class DomainRelation is defined in schema")
        )
    }


    /// Access the `EntityGlossaryRow` class builder.
    pub fn EntityGlossaryRow(&self) -> EntityGlossaryRowClassBuilder {
        EntityGlossaryRowClassBuilder::new(
            self.inner.get_class("EntityGlossaryRow")
                .expect("class EntityGlossaryRow is defined in schema")
        )
    }


    /// Access the `ExtractedRequirementSlot` class builder.
    pub fn ExtractedRequirementSlot(&self) -> ExtractedRequirementSlotClassBuilder {
        ExtractedRequirementSlotClassBuilder::new(
            self.inner.get_class("ExtractedRequirementSlot")
                .expect("class ExtractedRequirementSlot is defined in schema")
        )
    }


    /// Access the `PlanChatTurn` class builder.
    pub fn PlanChatTurn(&self) -> PlanChatTurnClassBuilder {
        PlanChatTurnClassBuilder::new(
            self.inner.get_class("PlanChatTurn")
                .expect("class PlanChatTurn is defined in schema")
        )
    }


    /// Access the `PlanComparison` class builder.
    pub fn PlanComparison(&self) -> PlanComparisonClassBuilder {
        PlanComparisonClassBuilder::new(
            self.inner.get_class("PlanComparison")
                .expect("class PlanComparison is defined in schema")
        )
    }


    /// Access the `PlasmPlan` class builder.
    pub fn PlasmPlan(&self) -> PlasmPlanClassBuilder {
        PlasmPlanClassBuilder::new(
            self.inner.get_class("PlasmPlan")
                .expect("class PlasmPlan is defined in schema")
        )
    }


    /// Access the `RequirementSlotExtraction` class builder.
    pub fn RequirementSlotExtraction(&self) -> RequirementSlotExtractionClassBuilder {
        RequirementSlotExtractionClassBuilder::new(
            self.inner.get_class("RequirementSlotExtraction")
                .expect("class RequirementSlotExtraction is defined in schema")
        )
    }


    /// Access the `RequirementWitnessRow` class builder.
    pub fn RequirementWitnessRow(&self) -> RequirementWitnessRowClassBuilder {
        RequirementWitnessRowClassBuilder::new(
            self.inner.get_class("RequirementWitnessRow")
                .expect("class RequirementWitnessRow is defined in schema")
        )
    }


    /// Access the `RerankedDiscovery` class builder.
    pub fn RerankedDiscovery(&self) -> RerankedDiscoveryClassBuilder {
        RerankedDiscoveryClassBuilder::new(
            self.inner.get_class("RerankedDiscovery")
                .expect("class RerankedDiscovery is defined in schema")
        )
    }


    /// Access the `SeedPlanRow` class builder.
    pub fn SeedPlanRow(&self) -> SeedPlanRowClassBuilder {
        SeedPlanRowClassBuilder::new(
            self.inner.get_class("SeedPlanRow")
                .expect("class SeedPlanRow is defined in schema")
        )
    }


    /// Access the `SharedType` class builder.
    pub fn SharedType(&self) -> SharedTypeClassBuilder {
        SharedTypeClassBuilder::new(
            self.inner.get_class("SharedType")
                .expect("class SharedType is defined in schema")
        )
    }


    /// Access the `ValidationIssue` class builder.
    pub fn ValidationIssue(&self) -> ValidationIssueClassBuilder {
        ValidationIssueClassBuilder::new(
            self.inner.get_class("ValidationIssue")
                .expect("class ValidationIssue is defined in schema")
        )
    }


    /// Access the `WitnessSelectionAssessment` class builder.
    pub fn WitnessSelectionAssessment(&self) -> WitnessSelectionAssessmentClassBuilder {
        WitnessSelectionAssessmentClassBuilder::new(
            self.inner.get_class("WitnessSelectionAssessment")
                .expect("class WitnessSelectionAssessment is defined in schema")
        )
    }


    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================


    /// Access the `CapabilityKind` enum builder.
    pub fn CapabilityKind(&self) -> CapabilityKindEnumBuilder {
        CapabilityKindEnumBuilder::new(
            self.inner.get_enum("CapabilityKind")
                .expect("enum CapabilityKind is defined in schema")
        )
    }


    /// Access the `Cardinality` enum builder.
    pub fn Cardinality(&self) -> CardinalityEnumBuilder {
        CardinalityEnumBuilder::new(
            self.inner.get_enum("Cardinality")
                .expect("enum Cardinality is defined in schema")
        )
    }


    /// Access the `FieldType` enum builder.
    pub fn FieldType(&self) -> FieldTypeEnumBuilder {
        FieldTypeEnumBuilder::new(
            self.inner.get_enum("FieldType")
                .expect("enum FieldType is defined in schema")
        )
    }


    /// Access the `ParamLocation` enum builder.
    pub fn ParamLocation(&self) -> ParamLocationEnumBuilder {
        ParamLocationEnumBuilder::new(
            self.inner.get_enum("ParamLocation")
                .expect("enum ParamLocation is defined in schema")
        )
    }


    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> ::baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> ::baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> ::baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> ::baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> ::baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> ::baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> ::baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> ::baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &::baml::TypeDef, value: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&::baml::TypeDef]) -> ::baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> ::std::result::Result<(), ::baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> ::std::string::String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(&self, name: &str) -> ::std::result::Result<::baml::EnumBuilder, ::baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> ::std::option::Option<::baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> ::std::vec::Vec<::baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(&self, name: &str) -> ::std::result::Result<::baml::ClassBuilder, ::baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> ::std::option::Option<::baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> ::std::vec::Vec<::baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl ::std::default::Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl ::std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}