// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

use baml::__internal::serde;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum StreamTypes {
    BundleCoverageRow(BundleCoverageRow),

    CandidateSeedBundle(CandidateSeedBundle),

    DiscoveryRerankCandidate(DiscoveryRerankCandidate),

    DomainCapability(DomainCapability),

    DomainEntity(DomainEntity),

    DomainField(DomainField),

    DomainModel(DomainModel),

    DomainModelValidation(DomainModelValidation),

    DomainParameter(DomainParameter),

    DomainRelation(DomainRelation),

    EntityCapabilityEvidence(EntityCapabilityEvidence),

    IntentRequirement(IntentRequirement),

    PlanChatTurn(PlanChatTurn),

    PlasmPlan(PlasmPlan),

    RerankedDiscovery(RerankedDiscovery),

    SeedBundleProviderGroup(SeedBundleProviderGroup),

    SeedBundleRoot(SeedBundleRoot),

    SeedCoverageAssessment(SeedCoverageAssessment),

    SharedType(SharedType),

    ValidationIssue(ValidationIssue),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::BundleCoverageRow(_) => "BundleCoverageRow",

            StreamTypes::CandidateSeedBundle(_) => "CandidateSeedBundle",

            StreamTypes::DiscoveryRerankCandidate(_) => "DiscoveryRerankCandidate",

            StreamTypes::DomainCapability(_) => "DomainCapability",

            StreamTypes::DomainEntity(_) => "DomainEntity",

            StreamTypes::DomainField(_) => "DomainField",

            StreamTypes::DomainModel(_) => "DomainModel",

            StreamTypes::DomainModelValidation(_) => "DomainModelValidation",

            StreamTypes::DomainParameter(_) => "DomainParameter",

            StreamTypes::DomainRelation(_) => "DomainRelation",

            StreamTypes::EntityCapabilityEvidence(_) => "EntityCapabilityEvidence",

            StreamTypes::IntentRequirement(_) => "IntentRequirement",

            StreamTypes::PlanChatTurn(_) => "PlanChatTurn",

            StreamTypes::PlasmPlan(_) => "PlasmPlan",

            StreamTypes::RerankedDiscovery(_) => "RerankedDiscovery",

            StreamTypes::SeedBundleProviderGroup(_) => "SeedBundleProviderGroup",

            StreamTypes::SeedBundleRoot(_) => "SeedBundleRoot",

            StreamTypes::SeedCoverageAssessment(_) => "SeedCoverageAssessment",

            StreamTypes::SharedType(_) => "SharedType",

            StreamTypes::ValidationIssue(_) => "ValidationIssue",
        }
    }
}

impl<'de> serde::Deserialize<'de> for StreamTypes {
    fn deserialize<D: serde::Deserializer<'de>>(
        _deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom(
            "StreamTypes is not deserializable, as we cannot disambiguate the type.",
        ))
    }
}
