// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::{BamlDecode, __internal::serde::Serialize};
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DiscoveryRerankCandidate {



    pub rank: Option<i64>,



    pub entry_id: Option<String>,



    pub entity: Option<String>,



    pub capability_name: Option<String>,



    pub description: Option<String>,


}



impl ::std::convert::AsRef<DiscoveryRerankCandidate> for DiscoveryRerankCandidate {
    fn as_ref(&self) -> &DiscoveryRerankCandidate {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainCapability {



    pub name: Option<String>,



    pub kind: Option<types::CapabilityKind>,



    pub description: Option<String>,



    pub http_method: Option<String>,



    pub path_template: Option<String>,



    pub parameters: Vec<DomainParameter>,



    pub request_body_fields: Vec<DomainField>,



    pub response_entity: Option<String>,



    pub response_is_array: Option<bool>,


}



impl ::std::convert::AsRef<DomainCapability> for DomainCapability {
    fn as_ref(&self) -> &DomainCapability {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainEntity {



    pub name: Option<String>,



    pub description: Option<String>,



    pub id_field: Option<String>,



    pub id_type: Option<types::FieldType>,



    pub alternate_keys: Vec<String>,



    pub fields: Vec<DomainField>,



    pub relations: Vec<DomainRelation>,



    pub capabilities: Vec<DomainCapability>,


}



impl ::std::convert::AsRef<DomainEntity> for DomainEntity {
    fn as_ref(&self) -> &DomainEntity {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainField {



    pub name: Option<String>,



    pub field_type: Option<types::FieldType>,



    pub required: Option<bool>,



    pub description: Option<String>,



    pub shared_type_name: Option<String>,



    pub array_element_type: Option<types::FieldType>,



    pub ref_target_entity: Option<String>,


}



impl ::std::convert::AsRef<DomainField> for DomainField {
    fn as_ref(&self) -> &DomainField {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModel {



    pub entities: Vec<DomainEntity>,



    pub shared_types: Vec<SharedType>,


}



impl ::std::convert::AsRef<DomainModel> for DomainModel {
    fn as_ref(&self) -> &DomainModel {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModelValidation {



    pub overall_quality: Option<String>,



    pub issues: Vec<ValidationIssue>,



    pub suggestions: Vec<String>,


}



impl ::std::convert::AsRef<DomainModelValidation> for DomainModelValidation {
    fn as_ref(&self) -> &DomainModelValidation {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainParameter {



    pub name: Option<String>,



    pub location: Option<types::ParamLocation>,



    pub field_type: Option<types::FieldType>,



    pub required: Option<bool>,



    pub shared_type_name: Option<String>,



    pub description: Option<String>,



    pub ref_target_entity: Option<String>,


}



impl ::std::convert::AsRef<DomainParameter> for DomainParameter {
    fn as_ref(&self) -> &DomainParameter {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainRelation {



    pub name: Option<String>,



    pub target_entity: Option<String>,



    pub cardinality: Option<types::Cardinality>,



    pub foreign_key_field: Option<String>,



    pub evidence: Option<String>,


}



impl ::std::convert::AsRef<DomainRelation> for DomainRelation {
    fn as_ref(&self) -> &DomainRelation {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct EntityGlossaryRow {



    pub catalog: Option<String>,



    pub entity: Option<String>,



    pub description: Option<String>,


}



impl ::std::convert::AsRef<EntityGlossaryRow> for EntityGlossaryRow {
    fn as_ref(&self) -> &EntityGlossaryRow {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct ExtractedRequirementSlot {



    pub kind: Option<String>,



    pub entity_hint: Option<String>,



    pub wire: Option<String>,



    pub target: Option<String>,



    pub op: Option<String>,


}



impl ::std::convert::AsRef<ExtractedRequirementSlot> for ExtractedRequirementSlot {
    fn as_ref(&self) -> &ExtractedRequirementSlot {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct PlanChatTurn {



    pub role: Option<types::Union2KassistantOrKuser>,



    pub content: Option<String>,


}



impl ::std::convert::AsRef<PlanChatTurn> for PlanChatTurn {
    fn as_ref(&self) -> &PlanChatTurn {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct PlanComparison {



    pub choice: Option<String>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<PlanComparison> for PlanComparison {
    fn as_ref(&self) -> &PlanComparison {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct PlasmPlan {



    pub text: Option<String>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<PlasmPlan> for PlasmPlan {
    fn as_ref(&self) -> &PlasmPlan {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct RequirementSlotExtraction {



    pub slots: Vec<ExtractedRequirementSlot>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<RequirementSlotExtraction> for RequirementSlotExtraction {
    fn as_ref(&self) -> &RequirementSlotExtraction {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct RequirementWitnessRow {



    pub symbol: Option<String>,



    pub kind: Option<String>,



    pub catalog: Option<String>,



    pub entity: Option<String>,



    pub entity_description: Option<String>,



    pub detail: Option<String>,



    pub aliases: Option<String>,



    pub graph_note: Option<String>,



    pub seed_class: Option<String>,



    pub seed_nav: Option<String>,



    pub own_pair: Option<String>,



    pub own_end: Option<String>,


}



impl ::std::convert::AsRef<RequirementWitnessRow> for RequirementWitnessRow {
    fn as_ref(&self) -> &RequirementWitnessRow {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct RerankedDiscovery {



    pub ordered_ids: Vec<i64>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<RerankedDiscovery> for RerankedDiscovery {
    fn as_ref(&self) -> &RerankedDiscovery {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SeedPlanRow {



    pub symbol: Option<String>,



    pub seeds: Option<String>,



    pub covered_witnesses: Option<String>,


}



impl ::std::convert::AsRef<SeedPlanRow> for SeedPlanRow {
    fn as_ref(&self) -> &SeedPlanRow {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SharedType {



    pub name: Option<String>,



    pub description: Option<String>,



    pub values: Vec<String>,



    pub used_by: Vec<String>,


}



impl ::std::convert::AsRef<SharedType> for SharedType {
    fn as_ref(&self) -> &SharedType {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct ValidationIssue {



    pub severity: Option<String>,



    pub entity: Option<String>,



    pub description: Option<String>,


}



impl ::std::convert::AsRef<ValidationIssue> for ValidationIssue {
    fn as_ref(&self) -> &ValidationIssue {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct WitnessSelectionAssessment {



    pub decision: Option<String>,



    pub selected_witness_symbols: Vec<String>,



    pub uncovered_requirements: Vec<String>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<WitnessSelectionAssessment> for WitnessSelectionAssessment {
    fn as_ref(&self) -> &WitnessSelectionAssessment {
        self
    }
}

