// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod unions;
mod type_aliases;

pub use classes::*;
pub use unions::*;
pub use type_aliases::*;

use baml::__internal::serde as serde;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum StreamTypes {

    DiscoveryRerankCandidate(DiscoveryRerankCandidate),

    DomainCapability(DomainCapability),

    DomainEntity(DomainEntity),

    DomainField(DomainField),

    DomainModel(DomainModel),

    DomainModelValidation(DomainModelValidation),

    DomainParameter(DomainParameter),

    DomainRelation(DomainRelation),

    EntityGlossaryRow(EntityGlossaryRow),

    ExtractedRequirementSlot(ExtractedRequirementSlot),

    PlanChatTurn(PlanChatTurn),

    PlanComparison(PlanComparison),

    PlasmPlan(PlasmPlan),

    RequirementSlotExtraction(RequirementSlotExtraction),

    RequirementWitnessRow(RequirementWitnessRow),

    RerankedDiscovery(RerankedDiscovery),

    SeedPlanRow(SeedPlanRow),

    SharedType(SharedType),

    ValidationIssue(ValidationIssue),

    WitnessSelectionAssessment(WitnessSelectionAssessment),


}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            StreamTypes::DiscoveryRerankCandidate(_) => "DiscoveryRerankCandidate",

            StreamTypes::DomainCapability(_) => "DomainCapability",

            StreamTypes::DomainEntity(_) => "DomainEntity",

            StreamTypes::DomainField(_) => "DomainField",

            StreamTypes::DomainModel(_) => "DomainModel",

            StreamTypes::DomainModelValidation(_) => "DomainModelValidation",

            StreamTypes::DomainParameter(_) => "DomainParameter",

            StreamTypes::DomainRelation(_) => "DomainRelation",

            StreamTypes::EntityGlossaryRow(_) => "EntityGlossaryRow",

            StreamTypes::ExtractedRequirementSlot(_) => "ExtractedRequirementSlot",

            StreamTypes::PlanChatTurn(_) => "PlanChatTurn",

            StreamTypes::PlanComparison(_) => "PlanComparison",

            StreamTypes::PlasmPlan(_) => "PlasmPlan",

            StreamTypes::RequirementSlotExtraction(_) => "RequirementSlotExtraction",

            StreamTypes::RequirementWitnessRow(_) => "RequirementWitnessRow",

            StreamTypes::RerankedDiscovery(_) => "RerankedDiscovery",

            StreamTypes::SeedPlanRow(_) => "SeedPlanRow",

            StreamTypes::SharedType(_) => "SharedType",

            StreamTypes::ValidationIssue(_) => "ValidationIssue",

            StreamTypes::WitnessSelectionAssessment(_) => "WitnessSelectionAssessment",



        }
    }
}

impl<'de> serde::Deserialize<'de> for StreamTypes {
    fn deserialize<D: serde::Deserializer<'de>>(_deserializer: D) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom("StreamTypes is not deserializable, as we cannot disambiguate the type."))
    }
}