//! MCP language frontmatter rendering.

use super::*;

pub(crate) struct PromptContractSpec {
    symbolic: bool,
    include_search_line: bool,
    include_rich_string_guidance: bool,
    include_scoped_search_worked_example: bool,
    include_search_only_entity_pitfall: bool,
    include_federation_pitfall: bool,
}

/// Render the agent-facing Plasm language guide used by MCP initialize instructions.
///
/// Catalogue-specific `plasm_context` results still provide the active symbol table and may return
/// a narrower frontmatter for the exposed entity slice. This guide is deliberately generated by the
/// same renderer as those per-session TSV frontmatters so MCP tool docs do not carry a hand-written
/// copy of the grammar.
pub fn render_plasm_mcp_language_frontmatter() -> String {
    render_prompt_contract(PromptContractSpec {
        symbolic: true,
        include_search_line: true,
        include_rich_string_guidance: true,
        include_scoped_search_worked_example: false,
        include_search_only_entity_pitfall: true,
        include_federation_pitfall: true,
    })
}

pub(crate) fn cgs_slice_has_search_capability(cgs: &CGS, full_entities: &[&str]) -> bool {
    full_entities
        .iter()
        .any(|e| !cgs.find_capabilities(e, CapabilityKind::Search).is_empty())
}

/// True when any string field or capability parameter in the slice uses non-`short` semantics
/// (`markdown`, `html`, `document`, `json_text`, `blob`, …).
pub(crate) fn cgs_slice_has_structured_string_semantics(cgs: &CGS, full_entities: &[&str]) -> bool {
    let full_set: HashSet<&str> = full_entities.iter().copied().collect();
    for &e in full_entities {
        if let Some(ent) = cgs.get_entity(e) {
            for f in ent.fields.values() {
                let Ok(nv) = f.named_value(cgs) else {
                    continue;
                };
                if matches!(nv.field_type, FieldType::Blob) {
                    return true;
                }
                if matches!(nv.field_type, FieldType::String)
                    && f.effective_string_semantics(cgs)
                        .is_structured_or_multiline()
                {
                    return true;
                }
            }
        }
    }
    for cap in cgs.capabilities.values() {
        if !full_set.contains(cap.domain.as_str()) {
            continue;
        }
        let Some(is) = &cap.input_schema else {
            continue;
        };
        let InputType::Object { fields, .. } = &is.input_type else {
            continue;
        };
        for f in fields {
            let Ok(nv) = f.named_value(cgs) else {
                continue;
            };
            if matches!(nv.field_type, FieldType::Blob) {
                return true;
            }
            if matches!(nv.field_type, FieldType::String)
                && f.effective_string_semantics(cgs)
                    .is_structured_or_multiline()
            {
                return true;
            }
        }
    }
    false
}

pub(crate) fn cgs_slice_has_repository_issue_scoped_search(full_entities: &[&str]) -> bool {
    full_entities.contains(&"Repository") && full_entities.contains(&"Issue")
}

pub(crate) fn cgs_slice_all_entities_have_query<'b, F>(
    resolve: &mut F,
    full_entities: &[&str],
) -> bool
where
    F: FnMut(&str) -> &'b CGS,
{
    full_entities.iter().all(|e| {
        let cgs = resolve(e);
        !cgs.find_capabilities(e, CapabilityKind::Query).is_empty()
    })
}

pub(crate) fn prompt_contract_spec_resolved<'b, F>(
    resolve: &mut F,
    full_entities: &[&str],
    symbolic: bool,
    slice_hints: ContractSliceHints,
) -> PromptContractSpec
where
    F: FnMut(&str) -> &'b CGS,
{
    let include_search_line = full_entities.iter().any(|e| {
        let name = *e;
        cgs_slice_has_search_capability(resolve(name), &[name])
    });
    let include_rich_string_guidance = full_entities.iter().any(|e| {
        let name = *e;
        cgs_slice_has_structured_string_semantics(resolve(name), &[name])
    });
    let include_federation_pitfall = slice_hints.distinct_catalog_count > 1;
    PromptContractSpec {
        symbolic,
        include_search_line,
        include_rich_string_guidance,
        include_scoped_search_worked_example: cgs_slice_has_repository_issue_scoped_search(
            full_entities,
        ),
        include_search_only_entity_pitfall: !cgs_slice_all_entities_have_query(
            resolve,
            full_entities,
        ),
        include_federation_pitfall,
    }
}

pub(crate) fn symbolic_entity_form(symbolic: bool) -> &'static str {
    if symbolic {
        "e#"
    } else {
        "Entity"
    }
}

pub(crate) fn render_prompt_contract(spec: PromptContractSpec) -> String {
    render_prompt_contract_dense(spec)
}

#[cfg(test)]
pub(crate) fn prompt_contract_spec_minimal_for_test() -> PromptContractSpec {
    PromptContractSpec {
        symbolic: true,
        include_search_line: false,
        include_rich_string_guidance: false,
        include_scoped_search_worked_example: false,
        include_search_only_entity_pitfall: false,
        include_federation_pitfall: false,
    }
}

pub(crate) fn render_prompt_contract_dense(spec: PromptContractSpec) -> String {
    let entity = symbolic_entity_form(spec.symbolic);
    let projection = if spec.symbolic {
        "[p#,…]"
    } else {
        "[field,…]"
    };
    let get_form = if spec.symbolic {
        "e#(<id>) or e#(p#=<value>, p#=<value>)"
    } else {
        "Entity(<id>) or Entity(name=<value>, name=<value>)"
    };
    let query_form = if spec.symbolic {
        "e#{p#=<value>, …}"
    } else {
        "Entity{name=<value>, …}"
    };
    let query_all_form = entity;
    let nav_form = if spec.symbolic {
        "<receiver>.r# | <receiver>.wire"
    } else {
        "<receiver>.field"
    };
    let method_form = if spec.symbolic {
        "e#(<id>).m#() or e#(<id>).m#(p#=<value>, …)"
    } else {
        "Entity(<id>).method() or Entity(<id>).method(name=<value>, …)"
    };
    let create_form = if spec.symbolic {
        "e#.m#(p#=<value>, …)"
    } else {
        "Entity.method(name=<value>, …)"
    };
    let projection_form = if spec.symbolic {
        "e#(<id>)[p#,…]"
    } else {
        "Entity(<id>)[field,…]"
    };
    let scoped_form = if spec.symbolic {
        "e1{p14=e3(p5=<val>, p13=<val>), …} (inline) OR repo=e3(…); e1{p14=repo, …} (decomposed label ref)"
    } else {
        "Entity{scope_param=AnchorEntity(<id>)}"
    };
    let array_form = if spec.symbolic {
        "p#=[e#(<id>), …]"
    } else {
        "name=[Entity(<id>), …]"
    };
    let search_form = if spec.symbolic {
        "e#~\"text\"[{p#=…}]?"
    } else {
        "Entity~\"text\"[{filter=…}]?"
    };
    let entity_expr_rhs: &str = if spec.include_search_line {
        "query_all | get | query | relation | method | create_action | search"
    } else {
        "query_all | get | query | relation | method | create_action"
    };

    let mut s = String::new();
    s.push_str(TEACHING_VALID_EXPR_MARKER);
    s.push_str("\n\n");

    s.push_str("Output:\n");
    s.push_str(
        "- Emit only code: either one `plasm_expr`, or one multi-line `plasm_program` with bindings then final roots.\n\
- Do not emit prose, JSON wrappers, `return`, Markdown fences, or table rows.\n\
- Prefer bind → narrow/project/transform → few final roots when more than one step is needed.\n\n",
    );

    s.push_str("TSV table semantics:\n");
    s.push_str(
        "- Header is exactly `plasm_expr<TAB>Meaning`; every following row has exactly one tab delimiter.\n\
- Left cell is either executable syntax or metadata. Right cell is selection guidance only; never copy `Meaning` into output.\n\
- Executable rows start with an entity surface (`e#`/`Entity`). Copy their left-cell shape, then replace placeholders.\n\
- Metadata rows whose left cell is only `v#`/`value domain` define reusable value types. Metadata rows whose left cell is only `p#`/`field` define keyed slots. Metadata rows are never executable roots.\n\
- `Meaning` fragments joined by ` · ` stay inside `Meaning`; they are not operators.\n\n",
    );

    s.push_str("Symbol and fill rules:\n");
    if spec.symbolic {
        s.push_str(
            "- `e#` = entity surface; `m#` = method/action surface; `p#` = field/capability/query predicate; `r#` = declared relation navigation; `v#` = value-domain metadata only.\n\
            - Relation hops use `.wire` or `.r#` on a row-producing receiver — not `p#` in dotted navigation (`p#` in `e#{{…}}` is a filter/param).\n\
- Entity-ref slots in `Meaning` look like `ref:Zone · str · Zone identifier`: canonical entity, id wire type, short note — not `plasm_expr` syntax.\n\
- Never write `v#` inside a `plasm_expr`. Use `p#` keys in code and use `v#` rows only to understand allowed values/types.\n\
- Unary identity rows often teach `e#(p#)` using the opaque `p#` for the entity `id_field` (same token as gloss); substitute the real wire id — do not treat it as a literal API value.\n\
- `<id>`, `<value>`, `<receiver>`, and `elem` in this contract are meta-variables, not syntax tokens.\n\
- If a copied row contains `..`, it is an ellipsis for omitted optional keys. Remove `..` or replace it with additional `p#=<value>` assignments before final output.\n\
- If `Meaning` says `opt: pA, pB`, those keys may be added only as keyed assignments with real values.\n",
        );
    } else {
        s.push_str(
            "- Entity names, method names, and field names are literal code tokens when they appear in executable left cells.\n\
- `$`, `<id>`, `<value>`, `<receiver>`, and `elem` are fill/meta placeholders; replace them before final output.\n\
- If a copied row contains `..`, remove it or replace it with additional keyed assignments before final output.\n",
        );
    }
    let _ = writeln!(
        s,
        "- Projection rows ending `{projection}` teach a valid field set. Reuse that suffix only on another expression returning the same entity or list type.",
        projection = projection
    );
    s.push_str("- Host continuations (`page`/`wait`/`cancel`/`pcN`): copy handles from prior responses (see Grammar). Open `oN`/`pgN` handles must be polled with `wait(h)` or cancelled before unrelated live execute or telling the user the task is done.\n\n");

    s.push_str("Grammar:\n");
    let _ = writeln!(s, "plasm_program ::= plasm_expr | binding+ roots");
    let _ = writeln!(s, "binding       ::= ident \"=\" node");
    let _ = writeln!(s, "roots         ::= root (\",\" root)*");
    let _ = writeln!(s, "root          ::= ident | plasm_expr");
    let _ = writeln!(
        s,
        "node          ::= (plasm_expr | ident) postfix* row_template? | ident \"=>\" value_or_template"
    );
    let _ = writeln!(
        s,
        "plasm_expr    ::= entity_expr [projection] | page | wait | cancel"
    );
    let _ = writeln!(s, "entity_expr   ::= {}", entity_expr_rhs);
    let _ = writeln!(s, "query_all     ::= {}", query_all_form);
    let _ = writeln!(s, "get           ::= {}", get_form);
    let _ = writeln!(s, "query         ::= {}", query_form);
    let _ = writeln!(s, "relation      ::= {}", nav_form);
    let _ = writeln!(s, "method        ::= {}", method_form);
    let _ = writeln!(s, "create_action ::= {}", create_form);
    if spec.include_search_line {
        let _ = writeln!(s, "search        ::= {}", search_form);
    }
    let _ = writeln!(
        s,
        "page          ::= page(l_<token>_pgM) | page(l_<token>_pgM, limit=N)"
    );
    let _ = writeln!(s, "wait          ::= wait(l_<token>_oM)");
    let _ = writeln!(s, "cancel        ::= cancel(l_<token>_oM)");
    let _ = writeln!(
        s,
        "projection    ::= {} | \"[\" fields \"]\"",
        projection_form
    );
    let _ = writeln!(
        s,
        "postfix       ::= \".limit(N)\" | \".page_size(N)\" | \".sort(field[, dir])\" | \".filter{{…}}\" | \".filter(…)\" | \".aggregate(specs)\" | \".group_by(field, specs)\" | \".dedupe(field[, …])\" | \".distinct(field[, …])\" | \".distinct()\" | \".singleton()\" | \"[\" fields \"]\""
    );
    let _ = writeln!(
        s,
        "row_template  ::= (\"[\" fields \"]\")? \"<<TAG\" template_body \"TAG\""
    );
    let _ = writeln!(s, "fields        ::= {}", projection);
    let _ = writeln!(
        s,
        "specs         ::= name=count | name=sum(field) | name=avg(field) | name=min(field) | name=max(field) | name=first(field) | name=last(field) [, ...]"
    );
    let _ = writeln!(s, "dir           ::= desc | asc | descending | ascending");
    let _ = writeln!(
        s,
        "value_or_template ::= literal | ident | ident.field | _.field | [elem, ...] | heredoc"
    );
    let _ = writeln!(s, "literal       ::= quoted string | number | bool | null");
    s.push('\n');

    s.push_str("Composition rules:\n");
    s.push_str(
        "- Multi-line programs: one binding per line and final roots last (preferred). Single-line space-separated bindings are coerced; default return is the first binding.\n\
- Postfix transforms and `[fields]` may chain on any bound node or expression that returns rows.\n\
- Row text: `report = rows[p#,…] <<TAG` newline template newline `TAG`; Minijinja `rows` is only that source's projected rows.\n\
- Compose text with `${report.content}` in later heredocs/strings; pass `binding.content` to string params, not the whole row.\n\
- Do not use `report.content` as a final root or relation receiver. Return `report` if you want the generated text row; continue relations only from row-producing query/relation/projection bindings.\n\
- Heredoc opener `<<TAG` is followed by newline; the first later line whose trimmed text is `TAG` closes it. Choose a tag not present in the body.\n",
    );
    let _ = writeln!(
        s,
        "- Examples: scoped child list `{scoped_form}`; array argument `{array_form}`. Quoted strings use only `\\\"` and `\\\\` escapes.",
        scoped_form = scoped_form,
        array_form = array_form
    );
    if spec.symbolic && spec.include_scoped_search_worked_example {
        s.push_str(
            "- Worked scoped-search program (copy shape, substitute values):\n\
  repo = e3(p5=octocat, p13=Hello-World)\n\
  e1{p14=repo, p71=open}\n\
  OR inline: e1{p14=e3(p5=octocat, p13=Hello-World), p71=open}\n",
        );
    }
    if spec.include_rich_string_guidance {
        s.push_str(&render_rich_string_guidance_tsv());
    }
    s.push('\n');

    s.push_str("Common pitfalls:\n");
    s.push_str(
        "- Row contract: `{…}` / `~\"…\"{…}` inputs fetch or filter rows; only `rows:` fields from the teaching row may be used in `[fields]`, `.group_by`, `.sort`, `.dedupe`, or row `.filter`.\n\
- Fetch vs row filter: `e#{{…}}` filters at HTTP; `binding.filter{{…}}` or `binding.filter(…)` filters materialized rows. Not `rows{{…}}` on a label.\n\
- `group_by(key, count=count)`; bare `group_by(key)` means `count=count`. Multi-key: `group_by(k1, k2, n=count)`.\n\
- Binding `=>`: only `rows => {{ k: _.field }}` (derive) or `rows => e1(…).update(…)` (for_each). Child reads: `labels = issues.r#` or `issues.labels` — not `issues => e2(…)`. Row text: `rows <<TAG`, not `=>`.\n\
- Homograph / gloss: filter `p#` and relation `.r#`/wire may share a wire name — fanout via `.r#`/wire (`labels = issues.p#` forgiven when the binding name matches). Copy executable left cells, not `Meaning` arrow gloss (`relation e3 → e2`).\n\
- Fill-ins: never emit `$` from teaching rows; substitute real ids, filter keys, and `e#~\"text\"` terms before execute.\n",
    );
    if spec.include_federation_pitfall {
        s.push_str(
            "- Federated sessions: use the `e#` from the teaching row for that catalog when the same wire entity name appears in multiple APIs.\n",
        );
    }
    if spec.include_search_only_entity_pitfall {
        s.push_str(
            "- Search-only entities (no query capability): there is no `e#{}` list-all — use scoped `e#{p#=…}` filters and/or real `~\"…\"` search text.\n",
        );
    }
    s.push('\n');

    s
}

/// Heredoc rules for TSV prompts: same semantics as markdown — one minimal tagged exemplar.
pub(crate) fn render_rich_string_guidance_tsv() -> String {
    "- `markdown`/`html`/`document`/`json_text`/`blob` values (per `Meaning`): `<<TAG` … `TAG` only; e.g. `m#(..., p#=<<TXT` + newline body + `TXT` newline `)`.\n"
        .to_string()
}

pub(crate) fn comment_prefix_block(text: &str) -> String {
    let mut out = String::new();
    for line in text.lines() {
        if line.is_empty() {
            out.push_str("#\n");
        } else {
            let _ = writeln!(out, "# {line}");
        }
    }
    out
}

/// Returns [`None`] when `sym` is a synonym for an earlier opaque symbol with the same `meaning`:
/// caller skips emitting a duplicate gloss row. Otherwise returns the canonical symbol for this meaning.
pub(crate) fn meaning_canonical_sym_for_emit(
    meaning: &str,
    sym: &str,
    meaning_to_canonical: &mut HashMap<String, String>,
    sym_alias: &mut HashMap<String, String>,
) -> Option<String> {
    match meaning_to_canonical.entry(meaning.to_string()) {
        Entry::Occupied(e) => {
            let canonical = e.get().clone();
            if canonical == sym {
                Some(canonical)
            } else {
                sym_alias.insert(sym.to_string(), canonical);
                None
            }
        }
        Entry::Vacant(v) => {
            v.insert(sym.to_string());
            Some(sym.to_string())
        }
    }
}

pub(crate) fn merge_opaque_alias_maps(
    p: &HashMap<String, String>,
    v: &HashMap<String, String>,
) -> HashMap<String, String> {
    let mut rep = p.clone();
    for (k, val) in v {
        if let Some(existing) = rep.get(k) {
            debug_assert_eq!(
                existing, val,
                "opaque alias collision for key {k:?}: p-map vs v-map disagree"
            );
        }
        rep.insert(k.clone(), val.clone());
    }
    rep
}

pub(crate) fn teaching_expr_line_fingerprint(row: &TeachingExprLine) -> String {
    format!(
        "{}\x1f{}\x1f{}\x1f{}\x1f{}\x1f{}\x1f{}",
        row.expression,
        row.result_type,
        row.scope,
        row.optional_params,
        row.compact_args,
        row.description,
        row.is_projection_teaching as u8,
    )
}

pub(crate) fn rewrite_teaching_expr_line_opaque_tokens(
    row: &mut TeachingExprLine,
    rep: &HashMap<String, String>,
) {
    row.expression = crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.expression, rep);
    row.result_type = crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.result_type, rep);
    row.scope = crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.scope, rep);
    row.optional_params =
        crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.optional_params, rep);
    row.compact_args = crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.compact_args, rep);
    row.description = crate::symbol_tuning::rewrite_opaque_ident_tokens(&row.description, rep);
}

pub(crate) fn rewrite_field_gloss_opaque_tokens(
    g: &mut TeachingFieldGloss,
    rep: &HashMap<String, String>,
) {
    g.symbol = crate::symbol_tuning::rewrite_opaque_ident_tokens(&g.symbol, rep);
    g.field_type = crate::symbol_tuning::rewrite_opaque_ident_tokens(&g.field_type, rep);
    g.allowed_values = crate::symbol_tuning::rewrite_opaque_ident_tokens(&g.allowed_values, rep);
    g.description = crate::symbol_tuning::rewrite_opaque_ident_tokens(&g.description, rep);
}

/// Tracks `p#` / `v#` gloss lines emitted before teaching example rows (first-use only).
pub(crate) struct FieldGlossEmitState {
    pub(crate) registry_p_slot_compact_gloss: HashMap<String, String>,
    pub(crate) registry_compact_meaning_canonical_p: HashMap<String, String>,
    pub(crate) registry_p_sym_alias: HashMap<String, String>,
    pub(crate) registry_value_gloss_canonical_v: HashMap<String, String>,
    pub(crate) registry_v_sym_alias: HashMap<String, String>,
    pub(crate) non_registry_slots: HashMap<String, IdentMetadata>,
    pub(crate) defined_value_domains: HashSet<String>,
}

/// Shared per-render caches for teaching table table synthesis (line validation, gloss dedup, metadata).
pub(crate) struct TeachingSynthesisSession<'a> {
    line_valid_cache: HashMap<DomainLineValidCacheKey, DomainLineValidEntry>,
    line_valid_cache_seed: u64,
    gloss_emit_state: FieldGlossEmitState,
    map: Option<&'a SymbolMap>,
    map_arc: Option<std::sync::Arc<SymbolMap>>,
    ident_meta: Option<HashMap<crate::symbol_tuning::IdentMetaKey, IdentMetadata>>,
    surface_filter: Option<&'a ExposureSurface>,
    entity_catalog_ids: IndexMap<(&'a str, &'a str), ()>,
    collect_meta: bool,
}

impl<'a> TeachingSynthesisSession<'a> {
    fn new(
        line_valid_cache_seed: u64,
        map: Option<&'a SymbolMap>,
        map_arc: Option<std::sync::Arc<SymbolMap>>,
        ident_meta: Option<HashMap<crate::symbol_tuning::IdentMetaKey, IdentMetadata>>,
        surface_filter: Option<&'a ExposureSurface>,
        entity_catalog_ids: IndexMap<(&'a str, &'a str), ()>,
        collect_meta: bool,
    ) -> Self {
        Self {
            line_valid_cache: HashMap::with_capacity(8192),
            line_valid_cache_seed,
            gloss_emit_state: FieldGlossEmitState {
                registry_p_slot_compact_gloss: HashMap::new(),
                registry_compact_meaning_canonical_p: HashMap::new(),
                registry_p_sym_alias: HashMap::new(),
                registry_value_gloss_canonical_v: HashMap::new(),
                registry_v_sym_alias: HashMap::new(),
                non_registry_slots: HashMap::new(),
                defined_value_domains: HashSet::new(),
            },
            map,
            map_arc,
            ident_meta,
            surface_filter,
            entity_catalog_ids,
            collect_meta,
        }
    }

    fn apply_opaque_alias_rewrites(
        &self,
        teaching_blocks_out: &mut [EntityTeachingBlock],
        model_out: &mut [EntityTeachingPrompt],
    ) {
        let rep = merge_opaque_alias_maps(
            &self.gloss_emit_state.registry_p_sym_alias,
            &self.gloss_emit_state.registry_v_sym_alias,
        );
        if rep.is_empty() {
            return;
        }
        if self.collect_meta {
            debug_assert_eq!(
                teaching_blocks_out.len(),
                model_out.len(),
                "model rows must stay aligned with teaching blocks"
            );
            for (block, prompt) in teaching_blocks_out.iter_mut().zip(model_out.iter_mut()) {
                for g in &mut block.field_gloss_rows {
                    rewrite_field_gloss_opaque_tokens(g, &rep);
                }
                for row in &mut block.teaching_rows {
                    rewrite_teaching_expr_line_opaque_tokens(&mut row.teaching_expr, &rep);
                    row.meta.expression = crate::symbol_tuning::rewrite_opaque_ident_tokens(
                        &row.meta.expression,
                        &rep,
                    );
                }
                let mut seen = HashSet::new();
                let mut new_rows = Vec::new();
                let mut new_lines = Vec::new();
                for (row, meta) in block.teaching_rows.drain(..).zip(prompt.lines.drain(..)) {
                    let fp = teaching_expr_line_fingerprint(&row.teaching_expr);
                    if seen.insert(fp) {
                        new_rows.push(row);
                        new_lines.push(meta);
                    }
                }
                block.teaching_rows = new_rows;
                prompt.lines = new_lines;
            }
        } else {
            for block in teaching_blocks_out.iter_mut() {
                for g in &mut block.field_gloss_rows {
                    rewrite_field_gloss_opaque_tokens(g, &rep);
                }
                for row in &mut block.teaching_rows {
                    rewrite_teaching_expr_line_opaque_tokens(&mut row.teaching_expr, &rep);
                    row.meta.expression = crate::symbol_tuning::rewrite_opaque_ident_tokens(
                        &row.meta.expression,
                        &rep,
                    );
                }
                let mut seen = HashSet::new();
                block.teaching_rows.retain(|row| {
                    let fp = teaching_expr_line_fingerprint(&row.teaching_expr);
                    seen.insert(fp)
                });
            }
        }
    }
}

/// Per-entity field gloss rows built directly into [`TeachingFieldGloss`] (no compact transcript).
pub(crate) struct GlossScratch<'a> {
    pub(crate) field_gloss: &'a mut Vec<TeachingFieldGloss>,
    pub(crate) state: &'a mut FieldGlossEmitState,
    pub(crate) map: &'a SymbolMap,
    pub(crate) meta: &'a HashMap<IdentMetaKey, IdentMetadata>,
    pub(crate) catalog_entry_id: &'a str,
    pub(crate) entity: &'a str,
    pub(crate) cgs: &'a CGS,
}

impl GlossScratch<'_> {
    pub(crate) fn emit_before_teaching_example(
        &mut self,
        expr: &str,
        cap_legend: Option<&str>,
        result_gloss: Option<&str>,
    ) {
        emit_field_def_lines_before_example(
            self.field_gloss,
            expr,
            cap_legend,
            result_gloss,
            self.map,
            self.entity,
            self.catalog_entry_id,
            self.meta,
            self.state,
            self.cgs,
        );
    }
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn emit_field_def_lines_before_example(
    out: &mut Vec<TeachingFieldGloss>,
    expr: &str,
    cap_legend: Option<&str>,
    result_gloss: Option<&str>,
    map: &SymbolMap,
    entity: &str,
    catalog_entry_id: &str,
    ident_meta: &HashMap<IdentMetaKey, IdentMetadata>,
    state: &mut FieldGlossEmitState,
    cgs: &CGS,
) {
    let en = EntityName::from(entity.to_string());
    let cid = catalog_entry_id.to_string();
    for sym in crate::symbol_tuning::field_syms_for_teaching_row(expr, result_gloss, cap_legend) {
        let field_name = map.resolve_ident(&sym).unwrap_or(&sym);
        // Capability `p#` maps to a leaf expand key (e.g. `blocks`) that may equal a relation wire
        // name on the same entity — resolve metadata from the full param path + CGS, not relation gloss.
        let meta = map
            .capability_param_quad_for_p_sym(sym.as_str())
            .and_then(|(eid, dom, cap, path)| {
                if !eid.is_empty() && eid.as_str() != catalog_entry_id {
                    return None;
                }
                crate::symbol_tuning::ident_metadata_for_capability_input_path(
                    cgs,
                    dom.as_str(),
                    cap.as_str(),
                    path.as_str(),
                )
            })
            .or_else(|| {
                map.capability_param_key_for_p_sym(sym.as_str())
                    .and_then(|(dom, w)| {
                        ident_meta
                            .get(&(cid.clone(), dom.clone(), w.clone()))
                            .cloned()
                    })
            })
            .or_else(|| {
                ident_meta
                    .get(&(cid.clone(), en.clone(), field_name.to_string()))
                    .cloned()
            });

        // Registry-backed `value_ref` slots: dedupe `v#` by gloss body first, then `p#` by compact Meaning.
        // Rewrite embedded `v#` in compact strings using [`registry_v_sym_alias`] before `p#` dedupe.
        if let (Some(m), Some(vs)) = (&meta, map.value_sym_for_p_sym(sym.as_str())) {
            if let IdentMetadata::RegistryBacked { .. } = m {
                if let Some(vg) = map.value_domain_gloss_for_v_sym(vs) {
                    if let Some(v_canon) = meaning_canonical_sym_for_emit(
                        vg,
                        vs,
                        &mut state.registry_value_gloss_canonical_v,
                        &mut state.registry_v_sym_alias,
                    ) {
                        if state.defined_value_domains.insert(v_canon.clone()) {
                            push_teaching_field_gloss_row(
                                out,
                                v_canon.clone(),
                                vg,
                                entity,
                                catalog_entry_id,
                                Some(map),
                                Some(ident_meta),
                                Some(cgs),
                                false,
                            );
                        }
                    }
                    let compact_raw =
                        compact_p_slot_registry_description(map, sym.as_str(), m, cgs)
                            .unwrap_or_else(|| {
                                let w = crate::symbol_tuning::registry_backed_compact_wire_label(m);
                                let mut c = format!("{} · {}", vs, w);
                                let d = m.description().trim();
                                if !d.is_empty() {
                                    let t = crate::symbol_tuning::gloss_description_truncated(d);
                                    c = format!("{} · {} · {}", vs, w, t);
                                }
                                c
                            });
                    let compact = crate::symbol_tuning::rewrite_opaque_ident_tokens(
                        &compact_raw,
                        &state.registry_v_sym_alias,
                    );
                    let path_key = map
                        .capability_param_quad_for_p_sym(sym.as_str())
                        .map(|(_, _, _, path)| path)
                        .unwrap_or_else(|| m.wire_name().to_string());
                    let p_meaning_key = format!(
                        "{}\x1f{}\x1f{}\x1f{}",
                        compact,
                        m.catalog_entry_id(),
                        m.entity().as_str(),
                        path_key
                    );
                    if meaning_canonical_sym_for_emit(
                        &p_meaning_key,
                        sym.as_str(),
                        &mut state.registry_compact_meaning_canonical_p,
                        &mut state.registry_p_sym_alias,
                    )
                    .is_none()
                    {
                        state
                            .registry_p_slot_compact_gloss
                            .insert(sym.clone(), compact.clone());
                        continue;
                    }
                    if state
                        .registry_p_slot_compact_gloss
                        .get(&sym)
                        .is_some_and(|prev| prev == &compact)
                    {
                        continue;
                    }
                    state
                        .registry_p_slot_compact_gloss
                        .insert(sym.clone(), compact.clone());
                    push_teaching_field_gloss_row(
                        out,
                        sym.clone(),
                        &compact,
                        entity,
                        catalog_entry_id,
                        Some(map),
                        Some(ident_meta),
                        Some(cgs),
                        false,
                    );
                    continue;
                }
            }
        }

        let should_emit = match (&meta, state.non_registry_slots.get(&sym)) {
            (Some(m), None) => {
                state.non_registry_slots.insert(sym.clone(), (*m).clone());
                true
            }
            (Some(m), Some(prev)) if *prev != *m => {
                state.non_registry_slots.insert(sym.clone(), (*m).clone());
                true
            }
            (None, None) => {
                state.non_registry_slots.insert(
                    sym.clone(),
                    crate::symbol_tuning::IdentMetadata::SyntheticUnknown {
                        catalog_entry_id: cid.clone(),
                        entity: en.clone(),
                        wire_name: field_name.to_string(),
                        description: field_name.to_string(),
                    },
                );
                true
            }
            _ => false,
        };
        if should_emit {
            let gloss = match meta {
                Some(m) => m.render_gloss_with_cgs(Some(map), Some(cgs)),
                None => field_name.to_string(),
            };
            if sym.starts_with('p')
                && state
                    .registry_p_slot_compact_gloss
                    .get(sym.as_str())
                    .is_some_and(|prev| prev == &gloss)
            {
                continue;
            }
            if sym.starts_with('p') {
                state
                    .registry_p_slot_compact_gloss
                    .insert(sym.clone(), gloss.clone());
            }
            push_teaching_field_gloss_row(
                out,
                sym.clone(),
                &gloss,
                entity,
                catalog_entry_id,
                Some(map),
                Some(ident_meta),
                Some(cgs),
                false,
            );
        }
    }
}

/// Per-entity many-shot examples — `focus` still subsets *which* entities appear.
#[allow(clippy::too_many_arguments)]
pub(crate) fn render_teaching_table_resolved<'b, F>(
    mut resolve: F,
    full_entities: &[&str],
    map: Option<&SymbolMap>,
    map_arc: Option<std::sync::Arc<SymbolMap>>,
    exposure_for_ident: Option<&TeachingExposureSession>,
    teaching_blocks_out: &mut Vec<EntityTeachingBlock>,
    model_out: &mut Vec<EntityTeachingPrompt>,
    fill_model: bool,
    _include_contract_preamble: bool,
    emit_entity_blocks: Option<&[&str]>,
    emit_entity_keys: Option<&std::collections::BTreeSet<(String, String)>>,
    federated_blocks: Option<&[(String, &str)]>,
    federated_by_entry: Option<&'b IndexMap<String, &'b CGS>>,
) where
    F: FnMut(&str) -> &'b CGS,
{
    let line_valid_cache_seed = match exposure_for_ident {
        Some(exp) => prompt_line_valid_cache_seed_exposure(exp),
        None => full_entities
            .first()
            .map(|&ename| prompt_line_valid_cache_seed_cgs(resolve(ename)))
            .unwrap_or(0),
    };
    let entity_catalog_ids: IndexMap<(&str, &str), ()> = exposure_for_ident
        .map(exposure_qualified_catalog_ids)
        .unwrap_or_default();
    let surface_filter = exposure_for_ident.map(|e| &e.surface);
    let ident_meta = match (map, exposure_for_ident) {
        (Some(_), Some(exposure)) => {
            Some(exposure.ident_metadata_for_exposure_entities(full_entities))
        }
        (Some(_), None) => {
            let mut acc = HashMap::new();
            for &e in full_entities {
                let cgs = resolve(e);
                acc.extend(crate::symbol_tuning::build_ident_metadata(cgs, &[e]));
            }
            Some(acc)
        }
        _ => None,
    };

    let mut session = TeachingSynthesisSession::new(
        line_valid_cache_seed,
        map,
        map_arc,
        ident_meta,
        surface_filter,
        entity_catalog_ids,
        fill_model,
    );

    let render_one = |session: &mut TeachingSynthesisSession<'_>,
                      cgs: &CGS,
                      ename: &str,
                      catalog_entry_id: &str,
                      teaching_blocks_out: &mut Vec<EntityTeachingBlock>,
                      model_out: &mut Vec<EntityTeachingPrompt>| {
        let mut field_gloss_accum = Vec::new();
        let mut gloss_emit: Option<GlossScratch<'_>> =
            match (session.map, session.ident_meta.as_ref()) {
                (Some(m), Some(meta)) => Some(GlossScratch {
                    field_gloss: &mut field_gloss_accum,
                    state: &mut session.gloss_emit_state,
                    map: m,
                    meta,
                    catalog_entry_id,
                    entity: ename,
                    cgs,
                }),
                _ => None,
            };
        let block = collect_entity_teaching_block(
            cgs,
            ename,
            session.map,
            session.ident_meta.as_ref(),
            session.collect_meta,
            &mut session.line_valid_cache,
            session.line_valid_cache_seed,
            session.map_arc.clone(),
            &mut gloss_emit,
            session.surface_filter,
            Some(catalog_entry_id),
        );
        if block.teaching_rows.is_empty() {
            debug_assert!(
                    false,
                    "teaching block empty for entity {ename} — CGS::validate should have rejected this via cgs_expression_validate"
                );
            tracing::warn!(
                target: "plasm_core::prompt_render",
                entity = ename,
                "empty teaching block; schema should have failed CGS::validate"
            );
            return;
        }
        let mut seen_expr: HashSet<TeachingRowDedupeKey> = HashSet::new();
        let mut emitted_metas: Vec<TeachingLineMeta> = Vec::new();
        let mut kept_rows: Vec<EntityTeachingExprRow> = Vec::new();
        for row in block.teaching_rows {
            if seen_expr.insert(row.dedupe_key.clone()) {
                if session.collect_meta {
                    emitted_metas.push(row.meta.clone());
                }
                kept_rows.push(row);
            }
        }
        teaching_blocks_out.push(EntityTeachingBlock {
            heading: block.heading,
            field_gloss_rows: block.field_gloss_rows,
            teaching_rows: kept_rows,
        });
        if session.collect_meta {
            model_out.push(EntityTeachingPrompt {
                entity: ename.to_string(),
                lines: emitted_metas,
            });
        }
    };

    if let Some(blocks) = federated_blocks {
        let by_entry =
            federated_by_entry.expect("federated_by_entry required when federated_blocks is set");
        for (entry_id, ename) in blocks {
            if let Some(set) = emit_entity_keys {
                if !set.contains(&(entry_id.clone(), ename.to_string())) {
                    continue;
                }
            }
            let cgs = by_entry
                .get(entry_id.as_str())
                .copied()
                .expect("CGS for catalog entry id");
            render_one(
                &mut session,
                cgs,
                ename,
                entry_id.as_str(),
                teaching_blocks_out,
                model_out,
            );
        }
    } else {
        let block_iter: Vec<&str> = if let Some(e) = emit_entity_blocks {
            e.to_vec()
        } else {
            full_entities.to_vec()
        };
        for &ename in &block_iter {
            let cgs = resolve(ename);
            let catalog_entry_id_owned =
                catalog_entry_id_for_exposed_entity(&session.entity_catalog_ids, ename)
                    .map(str::to_string)
                    .or_else(|| cgs.entry_id.clone())
                    .unwrap_or_default();
            render_one(
                &mut session,
                cgs,
                ename,
                catalog_entry_id_owned.as_str(),
                teaching_blocks_out,
                model_out,
            );
        }
    }

    session.apply_opaque_alias_rewrites(teaching_blocks_out, model_out);
}

/// Per-entity many-shot examples using a single [`CGS`].
#[allow(clippy::too_many_arguments)]
pub(crate) fn render_teaching_table(
    cgs: &CGS,
    full_entities: &[&str],
    map: Option<&SymbolMap>,
    map_arc: Option<std::sync::Arc<SymbolMap>>,
    teaching_blocks_out: &mut Vec<EntityTeachingBlock>,
    model_out: &mut Vec<EntityTeachingPrompt>,
    fill_model: bool,
    include_contract_preamble: bool,
    emit_entity_blocks: Option<&[&str]>,
) {
    render_teaching_table_resolved(
        |_| cgs,
        full_entities,
        map,
        map_arc,
        None,
        teaching_blocks_out,
        model_out,
        fill_model,
        include_contract_preamble,
        emit_entity_blocks,
        None,
        None,
        None::<&IndexMap<String, &CGS>>,
    );
}
