// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};
use baml::__internal::serde as serde;

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Types {

    BundleCoverageRow(BundleCoverageRow),

    CandidateSeedBundle(CandidateSeedBundle),

    DiscoveryRerankCandidate(DiscoveryRerankCandidate),

    DomainCapability(DomainCapability),

    DomainEntity(DomainEntity),

    DomainField(DomainField),

    DomainModel(DomainModel),

    DomainModelValidation(DomainModelValidation),

    DomainParameter(DomainParameter),

    DomainRelation(DomainRelation),

    EntityCapabilityEvidence(EntityCapabilityEvidence),

    IntentRequirement(IntentRequirement),

    PlanChatTurn(PlanChatTurn),

    PlasmPlan(PlasmPlan),

    RerankedDiscovery(RerankedDiscovery),

    SeedBundleProviderGroup(SeedBundleProviderGroup),

    SeedBundleRoot(SeedBundleRoot),

    SeedCoverageAssessment(SeedCoverageAssessment),

    SharedType(SharedType),

    ValidationIssue(ValidationIssue),


    CapabilityKind(CapabilityKind),

    Cardinality(Cardinality),

    FieldType(FieldType),

    ParamLocation(ParamLocation),


    Union2KassistantOrKuser(Union2KassistantOrKuser),

}

impl ::baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Self::BundleCoverageRow(_) => "BundleCoverageRow",

            Self::CandidateSeedBundle(_) => "CandidateSeedBundle",

            Self::DiscoveryRerankCandidate(_) => "DiscoveryRerankCandidate",

            Self::DomainCapability(_) => "DomainCapability",

            Self::DomainEntity(_) => "DomainEntity",

            Self::DomainField(_) => "DomainField",

            Self::DomainModel(_) => "DomainModel",

            Self::DomainModelValidation(_) => "DomainModelValidation",

            Self::DomainParameter(_) => "DomainParameter",

            Self::DomainRelation(_) => "DomainRelation",

            Self::EntityCapabilityEvidence(_) => "EntityCapabilityEvidence",

            Self::IntentRequirement(_) => "IntentRequirement",

            Self::PlanChatTurn(_) => "PlanChatTurn",

            Self::PlasmPlan(_) => "PlasmPlan",

            Self::RerankedDiscovery(_) => "RerankedDiscovery",

            Self::SeedBundleProviderGroup(_) => "SeedBundleProviderGroup",

            Self::SeedBundleRoot(_) => "SeedBundleRoot",

            Self::SeedCoverageAssessment(_) => "SeedCoverageAssessment",

            Self::SharedType(_) => "SharedType",

            Self::ValidationIssue(_) => "ValidationIssue",


            Self::CapabilityKind(_) => "CapabilityKind",

            Self::Cardinality(_) => "Cardinality",

            Self::FieldType(_) => "FieldType",

            Self::ParamLocation(_) => "ParamLocation",


            Self::Union2KassistantOrKuser(_) => "Union2KassistantOrKuser",


        }
    }
}

impl<'de> serde::Deserialize<'de> for Types {
    fn deserialize<D: serde::Deserializer<'de>>(_deserializer: D) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom("Types is not deserializable, as we cannot disambiguate the type."))
    }
}