// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `BundleCoverageRow` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct BundleCoverageRowClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl BundleCoverageRowClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("BundleCoverageRow is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `requirement_index` field builder.
    pub fn property_requirement_index(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("requirement_index")
            .expect("BundleCoverageRow.requirement_index is statically defined in .baml and should always be present")
    }


    /// Access the `supporting_bundle_indexes` field builder.
    pub fn property_supporting_bundle_indexes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("supporting_bundle_indexes")
            .expect("BundleCoverageRow.supporting_bundle_indexes is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CandidateSeedBundle` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CandidateSeedBundleClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl CandidateSeedBundleClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("CandidateSeedBundle is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `bundle_index` field builder.
    pub fn property_bundle_index(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("bundle_index")
            .expect("CandidateSeedBundle.bundle_index is statically defined in .baml and should always be present")
    }


    /// Access the `catalogs` field builder.
    pub fn property_catalogs(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("catalogs")
            .expect("CandidateSeedBundle.catalogs is statically defined in .baml and should always be present")
    }


    /// Access the `roots` field builder.
    pub fn property_roots(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("roots")
            .expect("CandidateSeedBundle.roots is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DiscoveryRerankCandidate` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DiscoveryRerankCandidateClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DiscoveryRerankCandidateClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DiscoveryRerankCandidate is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `rank` field builder.
    pub fn property_rank(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("rank")
            .expect("DiscoveryRerankCandidate.rank is statically defined in .baml and should always be present")
    }


    /// Access the `entry_id` field builder.
    pub fn property_entry_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entry_id")
            .expect("DiscoveryRerankCandidate.entry_id is statically defined in .baml and should always be present")
    }


    /// Access the `entity` field builder.
    pub fn property_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entity")
            .expect("DiscoveryRerankCandidate.entity is statically defined in .baml and should always be present")
    }


    /// Access the `capability_name` field builder.
    pub fn property_capability_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("capability_name")
            .expect("DiscoveryRerankCandidate.capability_name is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DiscoveryRerankCandidate.description is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainCapability` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainCapabilityClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainCapabilityClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainCapability is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("DomainCapability.name is statically defined in .baml and should always be present")
    }


    /// Access the `kind` field builder.
    pub fn property_kind(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("kind")
            .expect("DomainCapability.kind is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DomainCapability.description is statically defined in .baml and should always be present")
    }


    /// Access the `http_method` field builder.
    pub fn property_http_method(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("http_method")
            .expect("DomainCapability.http_method is statically defined in .baml and should always be present")
    }


    /// Access the `path_template` field builder.
    pub fn property_path_template(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("path_template")
            .expect("DomainCapability.path_template is statically defined in .baml and should always be present")
    }


    /// Access the `parameters` field builder.
    pub fn property_parameters(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("parameters")
            .expect("DomainCapability.parameters is statically defined in .baml and should always be present")
    }


    /// Access the `request_body_fields` field builder.
    pub fn property_request_body_fields(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("request_body_fields")
            .expect("DomainCapability.request_body_fields is statically defined in .baml and should always be present")
    }


    /// Access the `response_entity` field builder.
    pub fn property_response_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("response_entity")
            .expect("DomainCapability.response_entity is statically defined in .baml and should always be present")
    }


    /// Access the `response_is_array` field builder.
    pub fn property_response_is_array(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("response_is_array")
            .expect("DomainCapability.response_is_array is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainEntity` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainEntityClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainEntityClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainEntity is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("DomainEntity.name is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DomainEntity.description is statically defined in .baml and should always be present")
    }


    /// Access the `id_field` field builder.
    pub fn property_id_field(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("id_field")
            .expect("DomainEntity.id_field is statically defined in .baml and should always be present")
    }


    /// Access the `id_type` field builder.
    pub fn property_id_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("id_type")
            .expect("DomainEntity.id_type is statically defined in .baml and should always be present")
    }


    /// Access the `alternate_keys` field builder.
    pub fn property_alternate_keys(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("alternate_keys")
            .expect("DomainEntity.alternate_keys is statically defined in .baml and should always be present")
    }


    /// Access the `fields` field builder.
    pub fn property_fields(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("fields")
            .expect("DomainEntity.fields is statically defined in .baml and should always be present")
    }


    /// Access the `relations` field builder.
    pub fn property_relations(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("relations")
            .expect("DomainEntity.relations is statically defined in .baml and should always be present")
    }


    /// Access the `capabilities` field builder.
    pub fn property_capabilities(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("capabilities")
            .expect("DomainEntity.capabilities is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainField` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainFieldClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainFieldClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainField is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("DomainField.name is statically defined in .baml and should always be present")
    }


    /// Access the `field_type` field builder.
    pub fn property_field_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("field_type")
            .expect("DomainField.field_type is statically defined in .baml and should always be present")
    }


    /// Access the `required` field builder.
    pub fn property_required(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("required")
            .expect("DomainField.required is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DomainField.description is statically defined in .baml and should always be present")
    }


    /// Access the `shared_type_name` field builder.
    pub fn property_shared_type_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("shared_type_name")
            .expect("DomainField.shared_type_name is statically defined in .baml and should always be present")
    }


    /// Access the `array_element_type` field builder.
    pub fn property_array_element_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("array_element_type")
            .expect("DomainField.array_element_type is statically defined in .baml and should always be present")
    }


    /// Access the `ref_target_entity` field builder.
    pub fn property_ref_target_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("ref_target_entity")
            .expect("DomainField.ref_target_entity is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainModel` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainModelClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainModelClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainModel is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `entities` field builder.
    pub fn property_entities(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entities")
            .expect("DomainModel.entities is statically defined in .baml and should always be present")
    }


    /// Access the `shared_types` field builder.
    pub fn property_shared_types(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("shared_types")
            .expect("DomainModel.shared_types is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainModelValidation` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainModelValidationClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainModelValidationClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainModelValidation is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `overall_quality` field builder.
    pub fn property_overall_quality(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("overall_quality")
            .expect("DomainModelValidation.overall_quality is statically defined in .baml and should always be present")
    }


    /// Access the `issues` field builder.
    pub fn property_issues(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("issues")
            .expect("DomainModelValidation.issues is statically defined in .baml and should always be present")
    }


    /// Access the `suggestions` field builder.
    pub fn property_suggestions(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("suggestions")
            .expect("DomainModelValidation.suggestions is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainParameter` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainParameterClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainParameterClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainParameter is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("DomainParameter.name is statically defined in .baml and should always be present")
    }


    /// Access the `location` field builder.
    pub fn property_location(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("location")
            .expect("DomainParameter.location is statically defined in .baml and should always be present")
    }


    /// Access the `field_type` field builder.
    pub fn property_field_type(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("field_type")
            .expect("DomainParameter.field_type is statically defined in .baml and should always be present")
    }


    /// Access the `required` field builder.
    pub fn property_required(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("required")
            .expect("DomainParameter.required is statically defined in .baml and should always be present")
    }


    /// Access the `shared_type_name` field builder.
    pub fn property_shared_type_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("shared_type_name")
            .expect("DomainParameter.shared_type_name is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("DomainParameter.description is statically defined in .baml and should always be present")
    }


    /// Access the `ref_target_entity` field builder.
    pub fn property_ref_target_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("ref_target_entity")
            .expect("DomainParameter.ref_target_entity is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `DomainRelation` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct DomainRelationClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl DomainRelationClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("DomainRelation is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("DomainRelation.name is statically defined in .baml and should always be present")
    }


    /// Access the `target_entity` field builder.
    pub fn property_target_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("target_entity")
            .expect("DomainRelation.target_entity is statically defined in .baml and should always be present")
    }


    /// Access the `cardinality` field builder.
    pub fn property_cardinality(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("cardinality")
            .expect("DomainRelation.cardinality is statically defined in .baml and should always be present")
    }


    /// Access the `foreign_key_field` field builder.
    pub fn property_foreign_key_field(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("foreign_key_field")
            .expect("DomainRelation.foreign_key_field is statically defined in .baml and should always be present")
    }


    /// Access the `evidence` field builder.
    pub fn property_evidence(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("evidence")
            .expect("DomainRelation.evidence is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `EntityCapabilityEvidence` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct EntityCapabilityEvidenceClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl EntityCapabilityEvidenceClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("EntityCapabilityEvidence is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `capability_name` field builder.
    pub fn property_capability_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("capability_name")
            .expect("EntityCapabilityEvidence.capability_name is statically defined in .baml and should always be present")
    }


    /// Access the `kind` field builder.
    pub fn property_kind(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("kind")
            .expect("EntityCapabilityEvidence.kind is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("EntityCapabilityEvidence.description is statically defined in .baml and should always be present")
    }


    /// Access the `lexical_score` field builder.
    pub fn property_lexical_score(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("lexical_score")
            .expect("EntityCapabilityEvidence.lexical_score is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `IntentRequirement` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct IntentRequirementClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl IntentRequirementClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("IntentRequirement is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `requirement_index` field builder.
    pub fn property_requirement_index(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("requirement_index")
            .expect("IntentRequirement.requirement_index is statically defined in .baml and should always be present")
    }


    /// Access the `text` field builder.
    pub fn property_text(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("text")
            .expect("IntentRequirement.text is statically defined in .baml and should always be present")
    }


    /// Access the `depends_on_indexes` field builder.
    pub fn property_depends_on_indexes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("depends_on_indexes")
            .expect("IntentRequirement.depends_on_indexes is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `PlanChatTurn` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct PlanChatTurnClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl PlanChatTurnClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("PlanChatTurn is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `role` field builder.
    pub fn property_role(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("role")
            .expect("PlanChatTurn.role is statically defined in .baml and should always be present")
    }


    /// Access the `content` field builder.
    pub fn property_content(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("content")
            .expect("PlanChatTurn.content is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `PlasmPlan` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct PlasmPlanClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl PlasmPlanClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("PlasmPlan is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `text` field builder.
    pub fn property_text(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("text")
            .expect("PlasmPlan.text is statically defined in .baml and should always be present")
    }


    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning")
            .expect("PlasmPlan.reasoning is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `RerankedDiscovery` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct RerankedDiscoveryClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl RerankedDiscoveryClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("RerankedDiscovery is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `ordered_ids` field builder.
    pub fn property_ordered_ids(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("ordered_ids")
            .expect("RerankedDiscovery.ordered_ids is statically defined in .baml and should always be present")
    }


    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning")
            .expect("RerankedDiscovery.reasoning is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SeedBundleProviderGroup` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SeedBundleProviderGroupClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SeedBundleProviderGroupClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SeedBundleProviderGroup is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `provider_index` field builder.
    pub fn property_provider_index(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("provider_index")
            .expect("SeedBundleProviderGroup.provider_index is statically defined in .baml and should always be present")
    }


    /// Access the `catalogs` field builder.
    pub fn property_catalogs(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("catalogs")
            .expect("SeedBundleProviderGroup.catalogs is statically defined in .baml and should always be present")
    }


    /// Access the `bundle_indexes` field builder.
    pub fn property_bundle_indexes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("bundle_indexes")
            .expect("SeedBundleProviderGroup.bundle_indexes is statically defined in .baml and should always be present")
    }


    /// Access the `capability_sketch` field builder.
    pub fn property_capability_sketch(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("capability_sketch")
            .expect("SeedBundleProviderGroup.capability_sketch is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SeedBundleRoot` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SeedBundleRootClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SeedBundleRootClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SeedBundleRoot is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `catalog` field builder.
    pub fn property_catalog(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("catalog")
            .expect("SeedBundleRoot.catalog is statically defined in .baml and should always be present")
    }


    /// Access the `entity` field builder.
    pub fn property_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entity")
            .expect("SeedBundleRoot.entity is statically defined in .baml and should always be present")
    }


    /// Access the `entity_description` field builder.
    pub fn property_entity_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entity_description")
            .expect("SeedBundleRoot.entity_description is statically defined in .baml and should always be present")
    }


    /// Access the `capabilities` field builder.
    pub fn property_capabilities(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("capabilities")
            .expect("SeedBundleRoot.capabilities is statically defined in .baml and should always be present")
    }


    /// Access the `relation_coverage` field builder.
    pub fn property_relation_coverage(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("relation_coverage")
            .expect("SeedBundleRoot.relation_coverage is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SeedCoverageAssessment` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SeedCoverageAssessmentClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SeedCoverageAssessmentClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SeedCoverageAssessment is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `requirements` field builder.
    pub fn property_requirements(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("requirements")
            .expect("SeedCoverageAssessment.requirements is statically defined in .baml and should always be present")
    }


    /// Access the `coverage_rows` field builder.
    pub fn property_coverage_rows(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("coverage_rows")
            .expect("SeedCoverageAssessment.coverage_rows is statically defined in .baml and should always be present")
    }


    /// Access the `reasoning` field builder.
    pub fn property_reasoning(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reasoning")
            .expect("SeedCoverageAssessment.reasoning is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SharedType` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SharedTypeClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SharedTypeClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SharedType is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `name` field builder.
    pub fn property_name(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("name")
            .expect("SharedType.name is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("SharedType.description is statically defined in .baml and should always be present")
    }


    /// Access the `values` field builder.
    pub fn property_values(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("values")
            .expect("SharedType.values is statically defined in .baml and should always be present")
    }


    /// Access the `used_by` field builder.
    pub fn property_used_by(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("used_by")
            .expect("SharedType.used_by is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `ValidationIssue` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct ValidationIssueClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl ValidationIssueClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("ValidationIssue is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `severity` field builder.
    pub fn property_severity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("severity")
            .expect("ValidationIssue.severity is statically defined in .baml and should always be present")
    }


    /// Access the `entity` field builder.
    pub fn property_entity(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("entity")
            .expect("ValidationIssue.entity is statically defined in .baml and should always be present")
    }


    /// Access the `description` field builder.
    pub fn property_description(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("description")
            .expect("ValidationIssue.description is statically defined in .baml and should always be present")
    }

}

