/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PlasmEngine {
  constructor()
  loadCatalog(catalogDir: string): JsCatalogInfo
  exposeSeeds(intent: string, seeds: Array<JsSeed>): JsTeachingResult
  introspectCatalog(entryId: string): string
  dryRun(program: string): JsDryRunResult
  discover(intent: string): JsDiscoverResult
  runPlan(planCommitRef: string): JsRunPlanResult
  runPlanLive(planCommitRef: string, transport: (request: JsTransportRequest) => JsTransportResponse | Promise<JsTransportResponse>): Promise<JsRunPlanResult>
}

export interface JsCatalogInfo {
  entryId: string
  catalogCgsHash: string
}

export interface JsDiscoverResult {
  markdown: string
}

export interface JsDryRunResult {
  planCommitRef: string
  summary: string
  compJson: string
}

export interface JsRunPlanResult {
  ok: boolean
  message: string
  rowsJson?: string
  metaJson?: string
}

export interface JsSeed {
  api: string
  entity: string
}

export interface JsTeachingResult {
  tsv: string
  deltaRefs: Array<string>
}

export interface JsTransportRequest {
  method: string
  url: string
  headers?: Record<string, string>
  body?: string
  entryId?: string
}

export interface JsTransportResponse {
  status: number
  body: string
  nextUrl?: string
}
