/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * In-process Plasm engine for NAPI.
 *
 * Each engine has a FIFO asynchronous admission queue. A live HTTP callback may
 * await JavaScript while retaining its session engine; queued callers yield the
 * executor instead of blocking it. Independent logical sessions remain concurrent.
 */
export declare class PlasmEngine {
  constructor(montyBinary?: string | undefined | null)
  loadCatalog(catalogDir: string): Promise<JsCatalogInfo>
  /** Activate the complete loaded manifest set using explicit deployment bindings. */
  activateDiscovery(deploymentId: string, bindingsJson: string): Promise<string>
  /**
   * Typed intent provenance with its current discovery need; selection runs
   * outside the execution mutex.
   */
  routeIntent(intentProvenanceJson: string, logicalSessionId?: string | undefined | null): Promise<string>
  exposeSeeds(intent: string, seeds: Array<JsSeed>): Promise<JsTeachingResult>
  introspectCatalog(entryId: string): Promise<string>
  dryRun(program: string, logicalSessionId?: string | undefined | null): Promise<JsDryRunResult>
  runPlan(planCommitRef: string, logicalSessionId?: string | undefined | null): Promise<JsRunPlanResult>
  runPlanLive(planCommitRef: string, transport: (request: JsTransportRequest) => JsTransportResponse | Promise<JsTransportResponse>, logicalSessionId?: string): Promise<JsRunPlanResult>
}

export interface JsCatalogInfo {
  entryId: string
  catalogCgsHash: string
}

export interface JsDryRunResult {
  planCommitRef: string
  summary: string
  compJson: string
  fusedCleanRead: boolean
}

export interface JsRunPlanResult {
  ok: boolean
  message: string
  rowsJson?: string
  metaJson?: string
  artifactsJson?: string
}

export interface JsSeed {
  api: string
  entity: string
}

export interface JsTeachingResult {
  prompt: string
  deltaRefs: Array<string>
}

export interface JsTransportRequest {
  /** Scoped credentials require the callback to reject HTTP redirects. */
  rejectRedirects: boolean
  requireHostAuth: boolean
  method: string
  url: string
  headers?: Record<string, string>
  body?: string
  entryId?: string
}

export interface JsTransportResponse {
  status: number
  body: string
  nextUrl?: string
}
