/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * In-process Plasm engine for NAPI.
 *
 * **Mutex law (full cutover):** `inner` / `sessions` are `std::sync::Mutex`
 * held only for short critical sections. Never hold them across JS host-transport
 * awaits. Occupancy is `Ready | Live` — concurrent live callers fail closed.
 */
export declare class PlasmEngine {
  constructor()
  loadCatalog(catalogDir: string): Promise<JsCatalogInfo>
  /** Activate the complete loaded manifest set using explicit deployment bindings. */
  activateDiscovery(deploymentId: string, bindingsJson: string): Promise<string>
  /** Intent-only new/extend; selection runs outside the execution mutex. */
  routeIntent(intent: string, logicalSessionId?: string | undefined | null, userRequests?: Array<string> | undefined | null): Promise<string>
  exposeSeeds(intent: string, seeds: Array<JsSeed>): Promise<JsTeachingResult>
  introspectCatalog(entryId: string): Promise<string>
  dryRun(program: string, logicalSessionId?: string | undefined | null): Promise<JsDryRunResult>
  runPlan(planCommitRef: string, logicalSessionId?: string | undefined | null): Promise<JsRunPlanResult>
  runPlanLive(planCommitRef: string, transport: (request: JsTransportRequest) => JsTransportResponse | Promise<JsTransportResponse>, logicalSessionId?: string): Promise<JsRunPlanResult>
}

export interface JsCatalogInfo {
  entryId: string
  catalogCgsHash: string
}

export interface JsDryRunResult {
  planCommitRef: string
  summary: string
  compJson: string
  fusedCleanRead: boolean
}

export interface JsRunPlanResult {
  ok: boolean
  message: string
  rowsJson?: string
  metaJson?: string
  artifactsJson?: string
}

export interface JsSeed {
  api: string
  entity: string
}

export interface JsTeachingResult {
  tsv: string
  deltaRefs: Array<string>
}

export interface JsTransportRequest {
  /** Scoped credentials require the callback to reject HTTP redirects. */
  rejectRedirects: boolean
  requireHostAuth: boolean
  method: string
  url: string
  headers?: Record<string, string>
  body?: string
  entryId?: string
}

export interface JsTransportResponse {
  status: number
  body: string
  nextUrl?: string
}
