/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PlasmEngine {
  constructor()
  loadCatalog(catalogDir: string): JsCatalogInfo
  exposeSeeds(intent: string, seeds: Array<JsSeed>): JsTeachingResult
  dryRun(program: string): JsDryRunResult
}

export interface JsCatalogInfo {
  entryId: string
  catalogCgsHash: string
}

export interface JsDryRunResult {
  planCommitRef: string
  summary: string
  compJson: string
}

export interface JsSeed {
  api: string
  entity: string
}

export interface JsTeachingResult {
  tsv: string
  deltaRefs: Array<string>
}
