// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Asynchronous BAML client with function-object pattern.

use crate::baml_client::{runtime::{get_runtime, FunctionOptions}, stream_types, types};
use baml::{AsyncStreamingCall, BamlEncode, BamlError};

// =============================================================================
// Convenience Builder Methods Macro
// =============================================================================

/// Implements convenience builder methods that delegate to `with_options`.
/// Requires the type to have:
/// - `options: FunctionOptions` field
/// - `fn with_options(&self, options: FunctionOptions) -> Self` method
macro_rules! impl_options_convenience_methods {
    ($name:ident) => {
        impl $name {
            pub fn with_collector(&self, collector: &baml::Collector) -> Self {
                self.with_options(self.options.clone().with_collector(collector))
            }

            pub fn with_collectors(&self, collectors: &[baml::Collector]) -> Self {
                self.with_options(self.options.clone().with_collectors(collectors))
            }

            pub fn with_cancellation_token(&self, token: Option<baml::CancellationToken>) -> Self {
                self.with_options(self.options.clone().with_cancellation_token(token))
            }

            pub fn with_type_builder(&self, tb: &super::super::type_builder::TypeBuilder) -> Self {
                self.with_options(self.options.clone().with_type_builder(tb))
            }

            pub fn with_env_var(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_env_var(key, value))
            }

            pub fn with_tag(&self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_tag(key, value))
            }

            pub fn with_client(&self, client_name: impl Into<String>) -> Self {
                self.with_options(self.options.clone().with_client(client_name))
            }

            pub fn with_client_registry(&self, registry: &baml::ClientRegistry) -> Self {
                self.with_options(self.options.clone().with_client_registry(registry))
            }
        }
    };
}

// =============================================================================
// Function Struct Macro (generates per-function struct with async methods)
// =============================================================================

macro_rules! baml_function_async {
    ($name:ident($($param:ident : $ptype:ty),* $(,)?) -> ($stream_ret:ty, $final_ret:ty)) => {
        #[derive(Clone)]
        pub struct $name {
            pub(crate) options: FunctionOptions,
        }

        impl $name {
            pub const fn new() -> Self {
                Self { options: FunctionOptions::new() }
            }

            fn with_options(&self, options: FunctionOptions) -> Self {
                Self { options }
            }

            // Terminal methods (async)
            pub async fn call(&self, $($param: $ptype),*) -> Result<$final_ret, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_async(stringify!($name), &args).await
            }

            pub fn stream(&self, $($param: $ptype),*) -> Result<AsyncStreamingCall<$stream_ret, $final_ret>, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*;
                get_runtime().call_function_stream_async(stringify!($name), &args)
            }

            pub fn parse(&self, response: &str) -> Result<$final_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, false)
            }

            pub fn parse_stream(&self, response: &str) -> Result<$stream_ret, BamlError> {
                get_runtime().parse(stringify!($name), response, true)
            }

            pub async fn build_request(&self, $($param: $ptype),*) -> Result<baml::HTTPRequest, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*
                    .arg("stream", false);
                get_runtime().build_request_async(stringify!($name), &args).await
            }

            pub async fn build_request_stream(&self, $($param: $ptype),*) -> Result<baml::HTTPRequest, BamlError> {
                let args = self.options.to_baml_args()
                    $(.arg(stringify!($param), $param.baml_encode()))*
                    .arg("stream", true);
                get_runtime().build_request_stream_async(stringify!($name), &args).await
            }
        }

        // Builder convenience methods (separate impl block via macro)
        impl_options_convenience_methods!($name);
    };
}

// =============================================================================
// Generate function structs
// =============================================================================



baml_function_async!(CompareSeedPlans(intent: impl AsRef<str> + BamlEncode, plan_a: &types::SeedPlanRow, plan_b: &types::SeedPlanRow, ) -> (stream_types::PlanComparison, types::PlanComparison));


baml_function_async!(ExtractDomainModel(api_summary: impl AsRef<str> + BamlEncode, ) -> (stream_types::DomainModel, types::DomainModel));


baml_function_async!(ExtractMissingEntities(api_summary: impl AsRef<str> + BamlEncode, missing_entity_names: impl AsRef<str> + BamlEncode, known_refs: impl AsRef<str> + BamlEncode, known_enums: impl AsRef<str> + BamlEncode, ) -> (stream_types::DomainModel, types::DomainModel));


baml_function_async!(ExtractMissingSharedTypes(api_summary: impl AsRef<str> + BamlEncode, existing_entities: impl AsRef<str> + BamlEncode, missing_type_issues: impl AsRef<str> + BamlEncode, ) -> (stream_types::DomainModel, types::DomainModel));


baml_function_async!(ExtractRequirementSlots(intent: impl AsRef<str> + BamlEncode, entity_glossary: &[types::EntityGlossaryRow], ) -> (stream_types::RequirementSlotExtraction, types::RequirementSlotExtraction));


baml_function_async!(RerankDiscoveryCandidates(intent: impl AsRef<str> + BamlEncode, candidates: &[types::DiscoveryRerankCandidate], ) -> (stream_types::RerankedDiscovery, types::RerankedDiscovery));


baml_function_async!(SelectRequirementWitnesses(intent: impl AsRef<str> + BamlEncode, brand_lock_catalogs: &[String], witnesses: &[types::RequirementWitnessRow], ) -> (stream_types::WitnessSelectionAssessment, types::WitnessSelectionAssessment));


baml_function_async!(TranslatePlan(messages: &[types::PlanChatTurn], ) -> (stream_types::PlasmPlan, types::PlasmPlan));


baml_function_async!(ValidateDomainModel(api_summary: impl AsRef<str> + BamlEncode, domain_model: impl AsRef<str> + BamlEncode, ) -> (stream_types::DomainModelValidation, types::DomainModelValidation));


// =============================================================================
// Client Struct
// =============================================================================

#[derive(Clone)]
pub struct BamlAsyncClient {
    options: FunctionOptions,
    
    pub CompareSeedPlans: CompareSeedPlans,
    
    pub ExtractDomainModel: ExtractDomainModel,
    
    pub ExtractMissingEntities: ExtractMissingEntities,
    
    pub ExtractMissingSharedTypes: ExtractMissingSharedTypes,
    
    pub ExtractRequirementSlots: ExtractRequirementSlots,
    
    pub RerankDiscoveryCandidates: RerankDiscoveryCandidates,
    
    pub SelectRequirementWitnesses: SelectRequirementWitnesses,
    
    pub TranslatePlan: TranslatePlan,
    
    pub ValidateDomainModel: ValidateDomainModel,
    
}

impl BamlAsyncClient {
    pub const fn new() -> Self {
        Self {
            options: FunctionOptions::new(),
            
            CompareSeedPlans: CompareSeedPlans::new(),
            
            ExtractDomainModel: ExtractDomainModel::new(),
            
            ExtractMissingEntities: ExtractMissingEntities::new(),
            
            ExtractMissingSharedTypes: ExtractMissingSharedTypes::new(),
            
            ExtractRequirementSlots: ExtractRequirementSlots::new(),
            
            RerankDiscoveryCandidates: RerankDiscoveryCandidates::new(),
            
            SelectRequirementWitnesses: SelectRequirementWitnesses::new(),
            
            TranslatePlan: TranslatePlan::new(),
            
            ValidateDomainModel: ValidateDomainModel::new(),
            
        }
    }

    /// Apply options to all functions. Returns a new client with the options set.
    pub fn with_options(&self, options: FunctionOptions) -> Self {
        Self {
            options: options.clone(),
            
            CompareSeedPlans: CompareSeedPlans { options: options.clone() },
            
            ExtractDomainModel: ExtractDomainModel { options: options.clone() },
            
            ExtractMissingEntities: ExtractMissingEntities { options: options.clone() },
            
            ExtractMissingSharedTypes: ExtractMissingSharedTypes { options: options.clone() },
            
            ExtractRequirementSlots: ExtractRequirementSlots { options: options.clone() },
            
            RerankDiscoveryCandidates: RerankDiscoveryCandidates { options: options.clone() },
            
            SelectRequirementWitnesses: SelectRequirementWitnesses { options: options.clone() },
            
            TranslatePlan: TranslatePlan { options: options.clone() },
            
            ValidateDomainModel: ValidateDomainModel { options: options.clone() },
            
        }
    }
}

// Builder convenience methods
impl_options_convenience_methods!(BamlAsyncClient);

pub static B: BamlAsyncClient = BamlAsyncClient::new();