// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{
    __internal::serde::{Deserialize, Serialize},
    BamlDecode, BamlEncode,
};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DiscoveryRerankCandidate {
    pub rank: i64,
    pub entry_id: String,
    pub entity: String,
    pub capability_name: String,
    pub description: String,
}

impl ::std::convert::AsRef<DiscoveryRerankCandidate> for DiscoveryRerankCandidate {
    fn as_ref(&self) -> &DiscoveryRerankCandidate {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainCapability {
    pub name: String,
    pub kind: CapabilityKind,
    pub description: Option<String>,
    pub http_method: String,
    pub path_template: String,
    pub parameters: Vec<DomainParameter>,
    pub request_body_fields: Vec<DomainField>,
    pub response_entity: Option<String>,
    pub response_is_array: bool,
}

impl ::std::convert::AsRef<DomainCapability> for DomainCapability {
    fn as_ref(&self) -> &DomainCapability {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainEntity {
    pub name: String,
    pub description: Option<String>,
    pub id_field: String,
    pub id_type: FieldType,
    pub alternate_keys: Vec<String>,
    pub fields: Vec<DomainField>,
    pub relations: Vec<DomainRelation>,
    pub capabilities: Vec<DomainCapability>,
}

impl ::std::convert::AsRef<DomainEntity> for DomainEntity {
    fn as_ref(&self) -> &DomainEntity {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainField {
    pub name: String,
    pub field_type: FieldType,
    pub required: bool,
    pub description: Option<String>,
    pub shared_type_name: Option<String>,
    pub array_element_type: Option<FieldType>,
    pub ref_target_entity: Option<String>,
}

impl ::std::convert::AsRef<DomainField> for DomainField {
    fn as_ref(&self) -> &DomainField {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModel {
    pub entities: Vec<DomainEntity>,
    pub shared_types: Vec<SharedType>,
}

impl ::std::convert::AsRef<DomainModel> for DomainModel {
    fn as_ref(&self) -> &DomainModel {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModelValidation {
    pub overall_quality: String,
    pub issues: Vec<ValidationIssue>,
    pub suggestions: Vec<String>,
}

impl ::std::convert::AsRef<DomainModelValidation> for DomainModelValidation {
    fn as_ref(&self) -> &DomainModelValidation {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainParameter {
    pub name: String,
    pub location: ParamLocation,
    pub field_type: FieldType,
    pub required: bool,
    pub shared_type_name: Option<String>,
    pub description: Option<String>,
    pub ref_target_entity: Option<String>,
}

impl ::std::convert::AsRef<DomainParameter> for DomainParameter {
    fn as_ref(&self) -> &DomainParameter {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct DomainRelation {
    pub name: String,
    pub target_entity: String,
    pub cardinality: Cardinality,
    pub foreign_key_field: Option<String>,
    pub evidence: String,
}

impl ::std::convert::AsRef<DomainRelation> for DomainRelation {
    fn as_ref(&self) -> &DomainRelation {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct EntityGlossaryRow {
    pub catalog: String,
    pub entity: String,
    pub description: String,
}

impl ::std::convert::AsRef<EntityGlossaryRow> for EntityGlossaryRow {
    fn as_ref(&self) -> &EntityGlossaryRow {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ExtractedRequirementSlot {
    pub kind: String,
    pub entity_hint: Option<String>,
    pub wire: Option<String>,
    pub target: Option<String>,
    pub op: Option<String>,
}

impl ::std::convert::AsRef<ExtractedRequirementSlot> for ExtractedRequirementSlot {
    fn as_ref(&self) -> &ExtractedRequirementSlot {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PlanChatTurn {
    pub role: Union2KassistantOrKuser,
    pub content: String,
}

impl ::std::convert::AsRef<PlanChatTurn> for PlanChatTurn {
    fn as_ref(&self) -> &PlanChatTurn {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PlanComparison {
    pub choice: String,
    pub reasoning: String,
}

impl ::std::convert::AsRef<PlanComparison> for PlanComparison {
    fn as_ref(&self) -> &PlanComparison {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct PlasmPlan {
    pub text: String,
    pub reasoning: String,
}

impl ::std::convert::AsRef<PlasmPlan> for PlasmPlan {
    fn as_ref(&self) -> &PlasmPlan {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RequirementSlotExtraction {
    pub slots: Vec<ExtractedRequirementSlot>,
    pub reasoning: String,
}

impl ::std::convert::AsRef<RequirementSlotExtraction> for RequirementSlotExtraction {
    fn as_ref(&self) -> &RequirementSlotExtraction {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RequirementWitnessRow {
    pub symbol: String,
    pub kind: String,
    pub catalog: String,
    pub entity: String,
    pub entity_description: String,
    pub detail: String,
    pub aliases: String,
    pub graph_note: String,
    pub seed_class: String,
    pub seed_nav: String,
    pub own_pair: String,
    pub own_end: String,
}

impl ::std::convert::AsRef<RequirementWitnessRow> for RequirementWitnessRow {
    fn as_ref(&self) -> &RequirementWitnessRow {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct RerankedDiscovery {
    pub ordered_ids: Vec<i64>,
    pub reasoning: String,
}

impl ::std::convert::AsRef<RerankedDiscovery> for RerankedDiscovery {
    fn as_ref(&self) -> &RerankedDiscovery {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SeedPlanRow {
    pub symbol: String,
    pub seeds: String,
    pub covered_witnesses: String,
}

impl ::std::convert::AsRef<SeedPlanRow> for SeedPlanRow {
    fn as_ref(&self) -> &SeedPlanRow {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SharedType {
    pub name: String,
    pub description: Option<String>,
    pub values: Vec<String>,
    pub used_by: Vec<String>,
}

impl ::std::convert::AsRef<SharedType> for SharedType {
    fn as_ref(&self) -> &SharedType {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct ValidationIssue {
    pub severity: String,
    pub entity: Option<String>,
    pub description: String,
}

impl ::std::convert::AsRef<ValidationIssue> for ValidationIssue {
    fn as_ref(&self) -> &ValidationIssue {
        self
    }
}

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct WitnessSelectionAssessment {
    pub decision: String,
    pub selected_witness_symbols: Vec<String>,
    pub uncovered_requirements: Vec<String>,
    pub reasoning: String,
}

impl ::std::convert::AsRef<WitnessSelectionAssessment> for WitnessSelectionAssessment {
    fn as_ref(&self) -> &WitnessSelectionAssessment {
        self
    }
}
