// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated enum types.

use baml::{
    BamlDecode, BamlEncode,
    __internal::serde::{Deserialize, Serialize},
};

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub enum CapabilityKind {
    QUERY,

    GET,

    CREATE,

    UPDATE,

    DELETE,

    ACTION,
}

impl ::std::default::Default for CapabilityKind {
    fn default() -> Self {
        Self::QUERY
    }
}

impl ::std::fmt::Display for CapabilityKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::QUERY => write!(f, "QUERY"),

            Self::GET => write!(f, "GET"),

            Self::CREATE => write!(f, "CREATE"),

            Self::UPDATE => write!(f, "UPDATE"),

            Self::DELETE => write!(f, "DELETE"),

            Self::ACTION => write!(f, "ACTION"),
        }
    }
}

impl ::std::str::FromStr for CapabilityKind {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {
            "QUERY" => ::std::result::Result::Ok(Self::QUERY),

            "GET" => ::std::result::Result::Ok(Self::GET),

            "CREATE" => ::std::result::Result::Ok(Self::CREATE),

            "UPDATE" => ::std::result::Result::Ok(Self::UPDATE),

            "DELETE" => ::std::result::Result::Ok(Self::DELETE),

            "ACTION" => ::std::result::Result::Ok(Self::ACTION),

            _ => ::std::result::Result::Err(()),
        }
    }
}

impl ::std::convert::AsRef<CapabilityKind> for CapabilityKind {
    fn as_ref(&self) -> &CapabilityKind {
        self
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub enum Cardinality {
    ONE,

    MANY,
}

impl ::std::default::Default for Cardinality {
    fn default() -> Self {
        Self::ONE
    }
}

impl ::std::fmt::Display for Cardinality {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::ONE => write!(f, "ONE"),

            Self::MANY => write!(f, "MANY"),
        }
    }
}

impl ::std::str::FromStr for Cardinality {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {
            "ONE" => ::std::result::Result::Ok(Self::ONE),

            "MANY" => ::std::result::Result::Ok(Self::MANY),

            _ => ::std::result::Result::Err(()),
        }
    }
}

impl ::std::convert::AsRef<Cardinality> for Cardinality {
    fn as_ref(&self) -> &Cardinality {
        self
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub enum FieldType {
    STRING,

    INTEGER,

    FLOAT,

    BOOLEAN,

    DATE,

    DATETIME,

    ENUM,

    ARRAY,

    ENTITY_REF,
}

impl ::std::default::Default for FieldType {
    fn default() -> Self {
        Self::STRING
    }
}

impl ::std::fmt::Display for FieldType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::STRING => write!(f, "STRING"),

            Self::INTEGER => write!(f, "INTEGER"),

            Self::FLOAT => write!(f, "FLOAT"),

            Self::BOOLEAN => write!(f, "BOOLEAN"),

            Self::DATE => write!(f, "DATE"),

            Self::DATETIME => write!(f, "DATETIME"),

            Self::ENUM => write!(f, "ENUM"),

            Self::ARRAY => write!(f, "ARRAY"),

            Self::ENTITY_REF => write!(f, "ENTITY_REF"),
        }
    }
}

impl ::std::str::FromStr for FieldType {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {
            "STRING" => ::std::result::Result::Ok(Self::STRING),

            "INTEGER" => ::std::result::Result::Ok(Self::INTEGER),

            "FLOAT" => ::std::result::Result::Ok(Self::FLOAT),

            "BOOLEAN" => ::std::result::Result::Ok(Self::BOOLEAN),

            "DATE" => ::std::result::Result::Ok(Self::DATE),

            "DATETIME" => ::std::result::Result::Ok(Self::DATETIME),

            "ENUM" => ::std::result::Result::Ok(Self::ENUM),

            "ARRAY" => ::std::result::Result::Ok(Self::ARRAY),

            "ENTITY_REF" => ::std::result::Result::Ok(Self::ENTITY_REF),

            _ => ::std::result::Result::Err(()),
        }
    }
}

impl ::std::convert::AsRef<FieldType> for FieldType {
    fn as_ref(&self) -> &FieldType {
        self
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub enum ParamLocation {
    PATH,

    QUERY,

    BODY,

    HEADER,
}

impl ::std::default::Default for ParamLocation {
    fn default() -> Self {
        Self::PATH
    }
}

impl ::std::fmt::Display for ParamLocation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::PATH => write!(f, "PATH"),

            Self::QUERY => write!(f, "QUERY"),

            Self::BODY => write!(f, "BODY"),

            Self::HEADER => write!(f, "HEADER"),
        }
    }
}

impl ::std::str::FromStr for ParamLocation {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {
            "PATH" => ::std::result::Result::Ok(Self::PATH),

            "QUERY" => ::std::result::Result::Ok(Self::QUERY),

            "BODY" => ::std::result::Result::Ok(Self::BODY),

            "HEADER" => ::std::result::Result::Ok(Self::HEADER),

            _ => ::std::result::Result::Err(()),
        }
    }
}

impl ::std::convert::AsRef<ParamLocation> for ParamLocation {
    fn as_ref(&self) -> &ParamLocation {
        self
    }
}
