// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
use baml::__internal::serde;
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Types {
    DiscoveryRerankCandidate(DiscoveryRerankCandidate),

    DomainCapability(DomainCapability),

    DomainEntity(DomainEntity),

    DomainField(DomainField),

    DomainModel(DomainModel),

    DomainModelValidation(DomainModelValidation),

    DomainParameter(DomainParameter),

    DomainRelation(DomainRelation),

    EntityGlossaryRow(EntityGlossaryRow),

    ExtractedRequirementSlot(ExtractedRequirementSlot),

    PlanChatTurn(PlanChatTurn),

    PlanComparison(PlanComparison),

    PlasmPlan(PlasmPlan),

    RequirementSlotExtraction(RequirementSlotExtraction),

    RequirementWitnessRow(RequirementWitnessRow),

    RerankedDiscovery(RerankedDiscovery),

    SeedPlanRow(SeedPlanRow),

    SharedType(SharedType),

    ValidationIssue(ValidationIssue),

    WitnessSelectionAssessment(WitnessSelectionAssessment),

    CapabilityKind(CapabilityKind),

    Cardinality(Cardinality),

    FieldType(FieldType),

    ParamLocation(ParamLocation),

    Union2KassistantOrKuser(Union2KassistantOrKuser),
}

impl ::baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Self::DiscoveryRerankCandidate(_) => "DiscoveryRerankCandidate",

            Self::DomainCapability(_) => "DomainCapability",

            Self::DomainEntity(_) => "DomainEntity",

            Self::DomainField(_) => "DomainField",

            Self::DomainModel(_) => "DomainModel",

            Self::DomainModelValidation(_) => "DomainModelValidation",

            Self::DomainParameter(_) => "DomainParameter",

            Self::DomainRelation(_) => "DomainRelation",

            Self::EntityGlossaryRow(_) => "EntityGlossaryRow",

            Self::ExtractedRequirementSlot(_) => "ExtractedRequirementSlot",

            Self::PlanChatTurn(_) => "PlanChatTurn",

            Self::PlanComparison(_) => "PlanComparison",

            Self::PlasmPlan(_) => "PlasmPlan",

            Self::RequirementSlotExtraction(_) => "RequirementSlotExtraction",

            Self::RequirementWitnessRow(_) => "RequirementWitnessRow",

            Self::RerankedDiscovery(_) => "RerankedDiscovery",

            Self::SeedPlanRow(_) => "SeedPlanRow",

            Self::SharedType(_) => "SharedType",

            Self::ValidationIssue(_) => "ValidationIssue",

            Self::WitnessSelectionAssessment(_) => "WitnessSelectionAssessment",

            Self::CapabilityKind(_) => "CapabilityKind",

            Self::Cardinality(_) => "Cardinality",

            Self::FieldType(_) => "FieldType",

            Self::ParamLocation(_) => "ParamLocation",

            Self::Union2KassistantOrKuser(_) => "Union2KassistantOrKuser",
        }
    }
}

impl<'de> serde::Deserialize<'de> for Types {
    fn deserialize<D: serde::Deserializer<'de>>(
        _deserializer: D,
    ) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom(
            "Types is not deserializable, as we cannot disambiguate the type.",
        ))
    }
}
