// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode, BamlSerde, __internal::serde::{Serialize, Deserialize}};
use super::*;


/// Generated from: ("user" | "assistant")
#[derive(Debug, Clone, BamlEncode, BamlDecode, BamlSerde, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[baml(union)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum Union2KassistantOrKuser {

#[baml(name = "string_user", literal_string = "user")]
    #[serde(with = "__baml_serde_union_literal_Union2KassistantOrKuser::Kuser")]
    Kuser,

#[baml(name = "string_assistant", literal_string = "assistant")]
    #[serde(with = "__baml_serde_union_literal_Union2KassistantOrKuser::Kassistant")]
    Kassistant,

}

impl ::std::convert::AsRef<Union2KassistantOrKuser> for Union2KassistantOrKuser {
    fn as_ref(&self) -> &Union2KassistantOrKuser {
        self
    }
}

impl ::std::default::Default for Union2KassistantOrKuser {
    fn default() -> Self {
        
           
            Self::Kuser
        
    }
}

