//! Bound read operands exercised identically by both source frontends.
use super::MatrixRow;
pub(crate) const ROWS: &[MatrixRow] = &[
MatrixRow { id: "lang_bound_get_field", program: "source = LangItem(\"i1\")\nout = LangItem(source.id)\nsource,out", surface_line: false, federated: false, features: &["bound_get_identity", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &["```tsv", "owner"], expect_live_error: None },
MatrixRow { id: "lang_bound_get_scalar", program: "source = LangItem(\"i1\")\nkey = source.id\nout = LangItem(key)\nsource,out", surface_line: false, federated: false, features: &["bound_get_identity", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &["```tsv", "owner"], expect_live_error: None },
MatrixRow { id: "lang_bound_query_field", program: "source = LangItem(\"i1\")\nout = LangItem{owner=source.owner}\nsource,out", surface_line: false, federated: false, features: &["bound_query_operand", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &["```tsv", "owner"], expect_live_error: None },
MatrixRow { id: "lang_bound_query_scalar", program: "source = LangItem(\"i1\")\nowner = source.owner\nout = LangItem{owner=owner}\nsource,out", surface_line: false, federated: false, features: &["bound_query_operand", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &["```tsv", "owner"], expect_live_error: None },
MatrixRow { id: "lang_iterate_bound_identity", program: "source = LangCursor(\"c1\")\nkey = source.id\ncur = LangCursor(key)\ndone = iterate cur step LangCursor(_.id).tick() until phase = \"done\" take 2\ndone", surface_line: false, federated: false, features: &["bound_iterate_identity", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &["```tsv", "phase", "operations:"], expect_live_error: None },
MatrixRow { id: "lang_bound_get_empty", program: "source = LangItem | where id = \"missing\" | take 1\nkey = source.id\nout = LangItem(key)\nout", surface_line: false, federated: false, features: &["bound_get_identity", "dry_live_parity"], min_node_results: 2, expect_markdown_substrings: &[], expect_live_error: Some("zero rows") },
];
