//! Core query / pipe / binding matrix rows.

use super::super::row::MatrixRow;

pub(crate) const ROWS: &[MatrixRow] = &[
    MatrixRow {
        id: "lang_group_then_global_aggregate",
        federated: false,
        features: &[
            "pipe_summarize",
            "pipe_summarize_by",
            "group_then_global_aggregate",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "total"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_distinct_projected_values",
        federated: false,
        features: &[
            "pipe_distinct",
            "distinct_projected_values",
            "pipe_select",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["alpha"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_field_bound_argument",
        federated: false,
        features: &["bounded_singleton_field_extract", "binding_continuation"],
        min_node_results: 4,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_field_bind",
        federated: false,
        features: &["bounded_singleton_field_extract", "binding_continuation"],
        min_node_results: 3,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_field_argument",
        federated: false,
        features: &["bounded_singleton_field_extract", "binding_continuation"],
        min_node_results: 3,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_field_empty_bind",
        federated: false,
        features: &["bounded_singleton_field_extract", "binding_continuation"],
        min_node_results: 3,
        expect_markdown_substrings: &[],
        expect_live_error: Some("zero rows"),
    },
    MatrixRow {
        id: "lang_take_one_field_empty_argument",
        federated: false,
        features: &["bounded_singleton_field_extract", "binding_continuation"],
        min_node_results: 3,
        expect_markdown_substrings: &[],
        expect_live_error: Some("zero rows"),
    },
    MatrixRow {
        id: "lang_query_all",
        federated: false,
        features: &["entity_query", "pagination_fetch_all_default"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_surface_line_limit",
        federated: false,
        features: &["surface_line_compile", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_first_limit",
        federated: false,
        features: &["bind_first_pipe_take", "pipe_take"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search",
        federated: false,
        features: &["entity_search"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "Alpha"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_miss",
        federated: false,
        features: &["entity_search", "search_text_not_exact_match"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_brace_q",
        federated: false,
        features: &["entity_search", "search_brace_owns_text"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "Alpha"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_by_id",
        federated: false,
        features: &["entity_get"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "i1"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_predicate_brace_owner",
        federated: false,
        features: &["predicate_brace_equality"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_predicate_brace_score_cmp",
        federated: false,
        features: &["pipe_where"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_limit_projection",
        federated: false,
        features: &["pipe_take", "pipe_select"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_sort_limit",
        federated: false,
        features: &["pipe_order_by", "pipe_take", "pipe_select"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "score"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_sort_asc",
        federated: false,
        features: &[
            "pipe_order_by",
            "pipe_order_by_ascending",
            "pipe_take",
            "pipe_select",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "score"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate",
        federated: false,
        features: &["pipe_summarize"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "n"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate_sugar_count",
        federated: false,
        features: &["aggregate_sugar_count", "pipe_summarize"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "count"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate_sum",
        federated: false,
        features: &["aggregate_sum", "pipe_summarize"],
        min_node_results: 1,
        // Aggregate label `sum(...)` is not spelled in short markdown; binding `t` is stable.
        expect_markdown_substrings: &["```tsv", "t"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by",
        federated: false,
        features: &["pipe_summarize_by", "pipe_summarize_chain"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_aggregate_chain",
        federated: false,
        features: &[
            "pipe_summarize_chain",
            "pipe_summarize_by_multi",
            "agg_first_last",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_sugar",
        federated: false,
        features: &["pipe_summarize_by_count", "pipe_summarize_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "count"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_multi",
        federated: false,
        features: &["pipe_summarize_by_multi", "pipe_summarize_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_then_group_by",
        federated: false,
        features: &["entity_search", "pipe_summarize_by", "search_then_group_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_then_group_by_team_key",
        federated: false,
        features: &["entity_search", "pipe_summarize_by", "search_then_group_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "team_key"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_row_filter_brace",
        federated: false,
        features: &["pipe_where", "bindings_assignment"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_binding_only_last",
        federated: false,
        features: &[
            "program_return_binding_only_last",
            "bindings_assignment",
            "pipe_take",
            "pipe_select",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_pipeline_filter_sort",
        federated: false,
        features: &[
            "program_return_pipeline_filter_sort",
            "pipe_where",
            "pipe_order_by",
            "pipe_take",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_consecutive_writes",
        federated: false,
        features: &[
            "program_return_consecutive_writes",
            "effect_create",
            "parallel_final_roots",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "witness"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_row_filter_paren",
        federated: false,
        features: &["pipe_where", "bindings_assignment"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_mul",
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "boost"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_div",
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "id"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_concat",
        federated: false,
        features: &[
            "pipe_select_compute",
            "bindings_assignment",
            "pipe_take",
            "pipe_where",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_when_len",
        federated: false,
        features: &[
            "pipe_select_compute",
            "bindings_assignment",
            "pipe_take",
            "pipe_where",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_literal_boolean_sugar",
        federated: false,
        features: &[
            "repair_literal_membership",
            "repair_boolean_filter",
            "pipe_where",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_boolean_rowset_sugar",
        federated: false,
        features: &[
            "repair_boolean_filter",
            "pipe_where_in_rowset",
            "pipe_where",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_in_rowset",
        federated: false,
        features: &[
            "pipe_where_in_rowset",
            "pipe_where",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_not_in_rowset",
        federated: false,
        features: &[
            "pipe_where_not_in_rowset",
            "pipe_where",
            "pipe_select",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_not_in_universe_left",
        federated: false,
        features: &[
            "pipe_where_not_in_universe",
            "pipe_where_not_in_rowset",
            "pipe_where",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alpha-two"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_not_in_universe_right",
        federated: false,
        features: &[
            "pipe_where_not_in_universe",
            "pipe_where_not_in_rowset",
            "pipe_where",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "stock-one"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_where_in_rowset_paren",
        federated: false,
        features: &[
            "pipe_where_in_rowset",
            "pipe_where",
            "pipe_select",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_rowset",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "pipe_where_in_rowset",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_rowset_alias",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "pipe_select_compute",
            "pipe_where_in_rowset",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_rowset_alias_distinct",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "pipe_select_compute",
            "pipe_where_in_rowset",
            "pipe_distinct",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_rowset_alias_existing",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "pipe_select_compute",
            "pipe_where_in_rowset",
            "pipe_select",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_empty_right",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "pipe_union_empty_right",
            "pipe_select",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alpha-one"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_required_selection_default",
        federated: false,
        features: &["required_selection_default", "entity_query"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "stock-one"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_required_selection_multi",
        federated: false,
        features: &["required_selection_default", "entity_query"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alpha-one", "alpha-two"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_required_selection_empty",
        federated: false,
        features: &["required_selection_default", "entity_query"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_union_rowset_paren",
        federated: false,
        features: &[
            "pipe_union_rowset",
            "parenthesized_row_expression",
            "pipe_where_in_rowset",
            "pipe_select",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_select_alias_where",
        federated: false,
        features: &[
            "pipe_select_alias_where",
            "pipe_select_compute",
            "pipe_where",
            "bindings_assignment",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_lines",
        federated: false,
        features: &["relation_from_parent_get"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "note"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_quoted_binding_literal",
        federated: false,
        features: &[
            "quoted_string_literal",
            "pipe_where",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_quoted_binding_field_literal",
        federated: false,
        features: &[
            "quoted_string_literal",
            "effect_update",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_query_singleton",
        federated: false,
        features: &["collect_singleton"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_tags_scoped",
        federated: false,
        features: &[
            "relation_from_parent_get",
            "relation_prefer_embed_hit",
            "relation_prefer_from_parent_get",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "item_id", "label"],
        expect_live_error: None,
    },
];
