//! Core query / pipe / binding matrix rows.

use super::super::row::MatrixRow;

pub(crate) const ROWS: &[MatrixRow] = &[
    MatrixRow {
        id: "lang_query_all",
        program: "LangItem",
        surface_line: false,
        federated: false,
        features: &["entity_query", "pagination_fetch_all_default"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_surface_line_limit",
        program: "LangItem | take 2",
        surface_line: true,
        federated: false,
        features: &["surface_line_compile", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_first_limit",
        program: "items = LangItem\nitems | take 3",
        surface_line: false,
        federated: false,
        features: &["bind_first_pipe_take", "pipe_take"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search",
        program: r#"LangItem~"Alpha""#,
        surface_line: false,
        federated: false,
        features: &["entity_search"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "Alpha"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_by_id",
        program: r#"LangItem("i1")"#,
        surface_line: false,
        federated: false,
        features: &["entity_get"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "i1"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_predicate_brace_owner",
        program: r#"LangItem{owner="alice"}"#,
        surface_line: false,
        federated: false,
        features: &["predicate_brace_equality"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_predicate_brace_score_cmp",
        program: r#"LangItem | where owner~"alice""#,
        surface_line: false,
        federated: false,
        features: &["pipe_where"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_limit_projection",
        program: "projected = LangItem | take 1 | select id, title\nprojected",
        surface_line: false,
        federated: false,
        features: &["pipe_take", "pipe_select"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_sort_limit",
        program: "LangItem | order by score desc | take 2 | select id, score",
        surface_line: false,
        federated: false,
        features: &["pipe_order_by", "pipe_take", "pipe_select"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "score"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_sort_asc",
        program: "LangItem | order by score asc | take 3 | select id, score",
        surface_line: false,
        federated: false,
        features: &["pipe_order_by", "pipe_order_by_ascending", "pipe_take", "pipe_select"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "score"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate",
        program: "LangItem | summarize n=count()",
        surface_line: false,
        federated: false,
        features: &["pipe_summarize"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "n"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate_sugar_count",
        program: "LangItem | summarize count=count()",
        surface_line: false,
        federated: false,
        features: &["aggregate_sugar_count", "pipe_summarize"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "count"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_aggregate_sum",
        program: "LangItem | summarize t=sum(score)",
        surface_line: false,
        federated: false,
        features: &["aggregate_sum", "pipe_summarize"],
        min_node_results: 1,
        // Aggregate label `sum(...)` is not spelled in short markdown; binding `t` is stable.
        expect_markdown_substrings: &["```tsv", "t"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by",
        program: "LangItem | summarize by owner n=count()",
        surface_line: false,
        federated: false,
        features: &["pipe_summarize_by", "pipe_summarize_chain"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_aggregate_chain",
        program: "LangItem | summarize by owner, score n=count(), title=first(title)",
        surface_line: false,
        federated: false,
        features: &["pipe_summarize_chain", "pipe_summarize_by_multi", "agg_first_last"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_sugar",
        program: "LangItem | summarize by owner count=count()",
        surface_line: false,
        federated: false,
        features: &["pipe_summarize_by_count", "pipe_summarize_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "count"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_multi",
        program: "LangItem | summarize by owner, score n=count()",
        surface_line: false,
        federated: false,
        features: &["pipe_summarize_by_multi", "pipe_summarize_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_then_group_by",
        program: "rows = LangItem~\"matrix\"\nby_owner = rows | summarize by owner count=count()\nby_owner",
        surface_line: false,
        federated: false,
        features: &["entity_search", "pipe_summarize_by", "search_then_group_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_search_then_group_by_team_key",
        program: "rows = LangItem~\"matrix\"{team_key=\"eng\"}\nby_team = rows | summarize by team_key count=count()\nby_team",
        surface_line: false,
        federated: false,
        features: &["entity_search", "pipe_summarize_by", "search_then_group_by"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "team_key"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_row_filter_brace",
        program: "items = LangItem\nfiltered = items | where owner=\"alice\"\nfiltered",
        surface_line: false,
        federated: false,
        features: &["pipe_where", "bindings_assignment"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_binding_only_last",
        program: "items = LangItem\nlimited = items | take 3 | select id, title",
        surface_line: false,
        federated: false,
        features: &[
            "program_return_binding_only_last",
            "bindings_assignment",
            "pipe_take",
            "pipe_select",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_pipeline_filter_sort",
        program: r#"items = LangItem
filtered = items | where owner="alice"
sorted = filtered | order by title | take 10 | select title, owner"#,
        surface_line: false,
        federated: false,
        features: &[
            "program_return_pipeline_filter_sort",
            "pipe_where",
            "pipe_order_by",
            "pipe_take",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_program_return_consecutive_writes",
        program: r#"newbranch = LangItem.create(title="branch-a", score=1, owner="witness")
newfile = LangItem.create(title="file-b", score=2, owner="witness")
newbranch, newfile"#,
        surface_line: false,
        federated: false,
        features: &[
            "program_return_consecutive_writes",
            "effect_create",
            "parallel_final_roots",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "witness"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_row_filter_paren",
        program: "items = LangItem\nfiltered = items | where owner=\"alice\"\nfiltered",
        surface_line: false,
        federated: false,
        features: &["pipe_where", "bindings_assignment"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_mul",
        program: "items = LangItem\nboosted = items | select id, boost = score * 2 | take 3\nboosted",
        surface_line: false,
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "boost"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_div",
        program: "items = LangItem\nhalved = items | select id, half = score / 2 | take 3\nhalved",
        surface_line: false,
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "half"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_concat",
        program: r#"items = LangItem | where owner="alice"
tagged = items | select tag = owner + owner | take 1
tagged"#,
        surface_line: false,
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take", "pipe_where"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alicealice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_with_when_len",
        program: r#"items = LangItem | where owner="alice"
labeled = items | select label = when(len(owner)>0, owner, title) | take 1
labeled"#,
        surface_line: false,
        federated: false,
        features: &["pipe_select_compute", "bindings_assignment", "pipe_take", "pipe_where"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_lines",
        program: r#"lines = LangItem("i1").lines
lines | select id, note"#,
        surface_line: false,
        federated: false,
        features: &["relation_from_parent_get"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "note"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_query_singleton",
        program: "LangItem | take 5.singleton()",
        surface_line: false,
        federated: false,
        features: &["collect_singleton"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_tags_scoped",
        program: r#"LangItem("i1").tags"#,
        surface_line: false,
        federated: false,
        features: &[
            "relation_from_parent_get",
            "relation_prefer_embed_hit",
            "relation_prefer_from_parent_get",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "item_id", "label"],
        expect_live_error: None,
    },
];
