//! Effects, foreach, iterate, render matrix rows.

use super::super::row::MatrixRow;

pub(crate) const ROWS: &[MatrixRow] = &[
    MatrixRow {
        id: "lang_relation_empty_fanout",
        federated: false,
        features: &["relation_empty_fanout", "dry_live_parity"],
        min_node_results: 2,
        expect_markdown_substrings: &["tags"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_one_chain",
        federated: false,
        features: &["relation_one_chain", "dry_live_parity"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "body"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_derived_shape",
        federated: false,
        features: &["bindings_assignment", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["value=i1"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_value_error_at_execution",
        federated: false,
        features: &["bindings_assignment", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &[],
        expect_live_error: Some("split_part"),
    },
    MatrixRow {
        id: "lang_render_projected_shape",
        federated: false,
        features: &["bindings_assignment", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["i"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_relation_shape",
        federated: false,
        features: &["bindings_assignment", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["relation_count="],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bindings_render",
        federated: false,
        features: &["bindings_assignment", "bracket_render", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["#", "```"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_split_part",
        federated: false,
        features: &[
            "bindings_assignment",
            "bracket_render",
            "render_minijinja_split_part",
            "per_row_render",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["split_part_ok=i"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_cross_binding_render",
        federated: false,
        features: &["bindings_assignment", "bracket_render", "per_row_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["Item:", "i1", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_content_into_create",
        federated: false,
        features: &[
            "bracket_render_content_ref",
            "effect_create",
            "bracket_render",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "render-pipe-owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_heredoc_binding",
        federated: false,
        features: &["static_heredoc_binding", "parallel_final_roots"],
        min_node_results: 2,
        expect_markdown_substrings: &["# Results", "hello-matrix", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_heredoc_into_create",
        federated: false,
        features: &[
            "heredoc_binding_string_param",
            "static_heredoc_binding",
            "effect_create",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["heredoc-string-owner", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_heredoc_body_with_equals",
        federated: false,
        features: &[
            "heredoc_body_with_equals",
            "static_heredoc_binding",
            "parallel_final_roots",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["# Results", "key = value", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_inline_heredoc_method_arg",
        federated: false,
        features: &["inline_heredoc_method_arg", "effect_create"],
        min_node_results: 1,
        expect_markdown_substrings: &["inline-heredoc"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_inline_heredoc_method_arg_same_line",
        federated: false,
        features: &["inline_heredoc_method_arg_same_line", "effect_create"],
        min_node_results: 1,
        expect_markdown_substrings: &["inline-same-line"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_inline_heredoc_method_arg_github_shape",
        federated: false,
        features: &["inline_heredoc_method_arg_github_shape", "effect_create"],
        min_node_results: 1,
        expect_markdown_substrings: &["## Problem", "documentation"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_method_invoke_field_ref",
        federated: false,
        features: &["bind_method_invoke_field_ref", "effect_update"],
        min_node_results: 3,
        expect_markdown_substrings: &["alice", "42", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_method_invoke",
        federated: false,
        features: &[
            "bounded_singleton_method_invoke",
            "effect_update",
            "pipe_take",
        ],
        min_node_results: 3,
        expect_markdown_substrings: &["after-take1", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_take_one_method_invoke_empty",
        federated: false,
        features: &["bounded_singleton_method_invoke", "effect_update"],
        min_node_results: 3,
        expect_markdown_substrings: &[],
        expect_live_error: Some("zero rows"),
    },
    MatrixRow {
        id: "lang_rows_each_method_invoke",
        federated: false,
        features: &[
            "row_identity_method_invoke",
            "for_each_effect",
            "effect_update",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["after-each", "```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_singleton_field_scalar",
        federated: false,
        features: &["bind_singleton_field_scalar", "binding_continuation"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_singleton_field_scalar",
        federated: false,
        features: &["get_singleton_field_scalar", "bind_singleton_field_scalar"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_singleton_field_argument",
        federated: false,
        features: &["get_singleton_field_scalar", "effect_update"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_singleton_field_password",
        federated: false,
        features: &["get_singleton_field_scalar"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "venmo-secret"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_get_singleton_field_empty",
        federated: false,
        features: &["get_singleton_field_scalar"],
        min_node_results: 1,
        expect_markdown_substrings: &[],
        expect_live_error: Some("zero rows"),
    },
    MatrixRow {
        id: "lang_derive_map_parallel",
        federated: false,
        features: &["derive_map", "parallel_final_roots"],
        min_node_results: 3,
        expect_markdown_substrings: &["# Results", "```tsv", "t"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_binding_continuation",
        federated: false,
        features: &["binding_continuation"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_pipe_select_row_fields",
        federated: false,
        features: &[
            "pipe_select_row_fields",
            "binding_continuation",
            "pipe_select",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "title"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_limit1_continuation",
        federated: false,
        features: &["bind_pipe_take_continuation", "pipe_take"],
        min_node_results: 3,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_filter_continuation",
        federated: false,
        features: &[
            "bind_pipe_where_continuation",
            "pipe_where",
            "binding_continuation",
        ],
        min_node_results: 3,
        expect_markdown_substrings: &["## tags (", "Result coverage:"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_many_from_plural_query",
        federated: false,
        features: &[
            "relation_many_from_plural",
            "relation_prefer_from_parent_get",
            "relation_prefer_embed_miss",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_prefer_embed_hit",
        federated: false,
        features: &[
            "relation_prefer_embed_hit",
            "relation_prefer_from_parent_get",
            "relation_from_parent_get",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "item_id", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_prefer_embed_miss",
        federated: false,
        features: &[
            "relation_prefer_embed_miss",
            "relation_prefer_from_parent_get",
            "relation_many_from_plural",
            "relation_query_scoped",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_plural_relation_opaque_p",
        federated: false,
        features: &[
            "binding_opaque_relation_ref",
            "relation_many_from_plural",
            "relation_prefer_from_parent_get",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_opaque_r_symbol",
        federated: false,
        features: &[
            "relation_opaque_r_symbol",
            "relation_many_from_plural",
            "relation_prefer_from_parent_get",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_homograph_lhs_coercion",
        federated: false,
        features: &[
            "homograph_lhs_coercion",
            "repair_sugar_homograph",
            "relation_many_from_plural",
            "relation_prefer_from_parent_get",
            "binding_continuation",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_relation_integer_scoped_bindings",
        federated: false,
        features: &[
            "relation_many_from_plural",
            "relation_query_scoped_bindings",
            "relation_binding_proof",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "label"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_then_sort_agg_column",
        federated: false,
        features: &[
            "pipe_summarize_by",
            "pipe_summarize_order_by",
            "pipe_order_by",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_dedupe",
        federated: false,
        features: &["pipe_distinct", "pipe_take"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_dedupe",
        federated: false,
        features: &["pipe_distinct", "entity_search", "search_then_group_by"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // RA-4 pipe factorization — monolith (inline stages).
    MatrixRow {
        id: "lang_ra4_pipe_monolith",
        federated: false,
        features: &[
            "ra4_pipe_factor",
            "pipe_where",
            "pipe_order_by",
            "pipe_take",
            "pipe_select",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    // RA-4 pipe factorization — bind cuts of the same stage spine.
    MatrixRow {
        id: "lang_ra4_pipe_bind_cut",
        federated: false,
        features: &[
            "ra4_pipe_factor",
            "pipe_where",
            "pipe_order_by",
            "pipe_take",
            "pipe_select",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 5,
        expect_markdown_substrings: &["```tsv", "alice"],
        expect_live_error: None,
    },
    // RA-4 apply factorization — inline `=>` derive.
    MatrixRow {
        id: "lang_ra4_apply_monolith",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_where",
            "pipe_take",
            "derive_map",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // RA-4 apply factorization — bind left then `=>`.
    MatrixRow {
        id: "lang_ra4_apply_bind_cut",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_where",
            "pipe_take",
            "derive_map",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // RA-4 apply — relation fanout monolith vs bind-cut.
    MatrixRow {
        id: "lang_ra4_apply_relation_monolith",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_take",
            "relation_many_from_plural",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_ra4_apply_relation_bind_cut",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_take",
            "relation_many_from_plural",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // RA-4 apply — render bind-cut (pipe⇒render monolith needs named collection alias; sealed via bind).
    MatrixRow {
        id: "lang_per_row_render_zero",
        federated: false,
        features: &["per_row_render", "bracket_render"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_per_row_render_many",
        federated: false,
        features: &["per_row_render", "bracket_render", "pipe_take"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "value"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_plain_template_foreach",
        federated: false,
        features: &[
            "plain_template_foreach",
            "static_heredoc_binding",
            "pipe_take",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["-"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_name_collision",
        federated: false,
        features: &["render_name_collision", "per_row_render"],
        min_node_results: 1,
        expect_markdown_substrings: &[],
        expect_live_error: Some("both a row field and a program binding"),
    },
    MatrixRow {
        id: "lang_render_content_plural_reject",
        federated: false,
        features: &["render_content_plural_reject", "bracket_render_content_ref"],
        min_node_results: 2,
        expect_markdown_substrings: &[],
        expect_live_error: Some("not a singleton"),
    },
    MatrixRow {
        id: "lang_per_row_arg_template",
        federated: false,
        features: &[
            "per_row_arg_template",
            "for_each_effect",
            "effect_update",
            "row_identity_method_invoke",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_aggregate_report",
        federated: false,
        features: &[
            "render_aggregate_report",
            "per_row_arg_template",
            "plain_template_foreach",
            "for_each_effect",
            "effect_update",
        ],
        min_node_results: 3,
        expect_markdown_substrings: &["-"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_render_undefined_field",
        federated: false,
        features: &["per_row_render"],
        min_node_results: 1,
        expect_markdown_substrings: &[],
        expect_live_error: Some("not a current-row field"),
    },
];
