//! Federated / RA4 / pagination matrix rows.

use super::super::row::MatrixRow;

pub(crate) const ROWS: &[MatrixRow] = &[
    MatrixRow {
        id: "lang_ra4_apply_render_bind_cut",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_select",
            "bracket_render",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "value", "#"],
        expect_live_error: None,
    },
    // RA-4 apply — for_each monolith vs bind-cut.
    MatrixRow {
        id: "lang_ra4_apply_foreach_monolith",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_select",
            "for_each_effect",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_ra4_apply_foreach_bind_cut",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "pipe_select",
            "for_each_effect",
            "bindings_assignment",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // Trap: derive body containing `.message` must stay derive (not for_each via `.m` substring).
    MatrixRow {
        id: "lang_ra4_apply_derive_message_field",
        federated: false,
        features: &[
            "ra4_apply_factor",
            "derive_map",
            "pipe_where",
            "pipe_take",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_group_by_first",
        federated: false,
        features: &["pipe_summarize_by", "agg_first_last"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_projection_then_relation",
        federated: false,
        features: &["bind_projection_then_relation", "pipe_select"],
        min_node_results: 3,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_relation_hop_one_one",
        federated: false,
        features: &[
            "relation_one_opaque_r",
            "bind_relation_hop_one_one",
            "dry_live_parity",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_effect_create_literal",
        federated: false,
        features: &["effect_create"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "MatrixCreated"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_money_predicate_gt",
        federated: false,
        features: &["money_predicate", "pipe_where"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_integer_where_gt_dry_coerce",
        federated: false,
        features: &["catalog_directed_coerce", "pipe_where", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_money_create_body",
        federated: false,
        features: &["money_create_body", "effect_create"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_effect_update",
        federated: false,
        features: &["effect_update"],
        min_node_results: 1,
        expect_markdown_substrings: &["MatrixPatch", "42"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_effect_action_ping",
        federated: false,
        features: &["effect_action"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "i1", "/langitem_ping`"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_effect_delete",
        federated: false,
        features: &["effect_delete"],
        min_node_results: 1,
        expect_markdown_substrings: &["/langitem_delete`", "1 completed."],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_for_each_empty_ping",
        federated: false,
        features: &["for_each_effect", "effect_action", "pipe_where"],
        min_node_results: 2,
        expect_markdown_substrings: &["No actions dispatched."],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_apply_get_multirow",
        federated: false,
        features: &[
            "row_apply_get",
            "pipe_where",
            "pipe_take",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "details"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_apply_query_multirow",
        federated: false,
        features: &[
            "row_apply_query",
            "pipe_where",
            "pipe_take",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["peers"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_for_each_update",
        federated: false,
        features: &["for_each_effect"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // Multi-row live mutator fanout (list source → N distinct PATCH identities).
    MatrixRow {
        id: "lang_for_each_multirow_update",
        federated: false,
        features: &[
            "for_each_effect",
            "for_each_multirow",
            "pipe_where",
            "pipe_take",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // Outer auth binding × multi-row secured mutator (Bearer from LangAuthSession.login).
    MatrixRow {
        id: "lang_for_each_auth_secured_touch",
        federated: false,
        features: &[
            "for_each_effect",
            "for_each_multirow",
            "for_each_auth_outer_binding",
            "pipe_where",
            "pipe_take",
            "dry_live_parity",
        ],
        min_node_results: 3,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    // PLP-8: seed phase=open; each tick advances open→mid→done; until holds within take.
    MatrixRow {
        id: "lang_iterate_until_bound",
        federated: false,
        features: &[
            "iterate_until_bound",
            "effect_action",
            "entity_get",
            "dry_live_parity",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "c1", "phase", "/langcursor_tick`"],
        expect_live_error: None,
    },
    // PLP-8: until already true on seed — zero steps.
    MatrixRow {
        id: "lang_iterate_until_zero_step",
        federated: false,
        features: &["iterate_until_zero_step", "entity_get", "dry_live_parity"],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "c_done", "phase"],
        expect_live_error: None,
    },
    // PLP-8: stuck cursor never reaches done — bound exhaustion is defined failure.
    MatrixRow {
        id: "lang_iterate_bound_exhausted",
        federated: false,
        features: &["iterate_bound_exhausted", "effect_action", "entity_get"],
        min_node_results: 1,
        expect_markdown_substrings: &[],
        expect_live_error: Some("iterate_bound_exhausted"),
    },
    MatrixRow {
        id: "lang_federated_relation_target_entry",
        federated: true,
        features: &[
            "federated_relation_target_entry",
            "relation_from_parent_get",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["summary"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_duplicate_entity_e1_query",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "domain_symbol_e1",
            "entity_query",
            "predicate_brace_equality",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_duplicate_entity_e2_search",
        federated: true,
        features: &["federated_duplicate_entity_symbol", "entity_search"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_duplicate_entity_relation_r",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "federated_duplicate_entity_relation_r",
            "relation_from_parent_get",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_duplicate_entity_mutator_m",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "federated_duplicate_entity_mutator_m",
            "effect_create",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_duplicate_entity_pathless_action",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "federated_duplicate_entity_pathless_action",
            "effect_action",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_auth_session_provides_mutation",
        federated: true,
        features: &[
            "federated_auth_session_provides_mutation",
            "federated_dual_auth_bearer_holes",
            "summary_hydrate_capability_params",
            "effect_action",
            "entity_search",
            "entity_query",
            "entity_get",
        ],
        min_node_results: 4,
        expect_markdown_substrings: &["```tsv", "note_id", "group_id"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_parallel_roots",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "federated_parallel_roots",
            "entity_query",
            "entity_search",
            "parallel_final_roots",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_federated_group_by_on_e1",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "federated_group_by_on_e1",
            "pipe_summarize_chain",
            "pipe_summarize_by",
        ],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_bind_template_inline_on_e1",
        federated: true,
        features: &[
            "federated_duplicate_entity_symbol",
            "bracket_render_inline_on_e",
            "bracket_render",
            "bindings_assignment",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["#"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_domain_symbol_page_size",
        federated: false,
        features: &["domain_symbol_e1", "pagination_page_size"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv", "owner"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_utf8_minijinja_content_stitch",
        federated: false,
        features: &[
            "utf8_minijinja_interpolate",
            "bracket_render",
            "bracket_render_content_ref",
            "effect_create",
            "bindings_assignment",
        ],
        min_node_results: 2,
        expect_markdown_substrings: &["```tsv", "utf8-matrix-owner", "Pokémon"],
        expect_live_error: None,
    },
];
