//! Exact scalar and compound identity constructors.
use super::MatrixRow;
pub(crate) const ROWS: &[MatrixRow] = &[
MatrixRow { id: "lang_boolean_identity_false", program: "LangItem(false) | select id", surface_line: false, federated: false, features: &["boolean_identity_literal", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_boolean_identity_true", program: "LangItem(true) | select id", surface_line: false, federated: false, features: &["boolean_identity_literal", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_integer_identity", program: "LangItem(42) | select id", surface_line: false, federated: false, features: &["exact_integer_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_negative_identity", program: "LangItem(-42) | select id", surface_line: false, federated: false, features: &["exact_integer_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_large_identity", program: "LangItem(9007199254740993) | select id", surface_line: false, federated: false, features: &["exact_integer_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_min_identity", program: "LangItem(-9223372036854775808) | select id", surface_line: false, federated: false, features: &["exact_integer_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_compound_literal", program: "out = CompoundBranch(owner=\"alice\", item_id=\"i1\", name=\"main\")\nout", surface_line: false, federated: false, features: &["compound_get_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
MatrixRow { id: "lang_compound_bound", program: "source = CompoundBranch(owner=\"alice\", item_id=\"i1\", name=\"main\")\nout = CompoundBranch(owner=source.owner, item_id=source.item_id, name=source.name)\nsource,out", surface_line: false, federated: false, features: &["compound_get_identity", "entity_get", "dry_live_parity"], min_node_results: 1, expect_markdown_substrings: &["```tsv"], expect_live_error: None },
];
