//! Exact scalar and compound identity constructors.
use super::MatrixRow;
pub(crate) const ROWS: &[MatrixRow] = &[
    MatrixRow {
        id: "lang_boolean_identity_false",
        federated: false,
        features: &["boolean_identity_literal", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_boolean_identity_true",
        federated: false,
        features: &["boolean_identity_literal", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_integer_identity",
        federated: false,
        features: &["exact_integer_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_negative_identity",
        federated: false,
        features: &["exact_integer_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_large_identity",
        federated: false,
        features: &["exact_integer_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_min_identity",
        federated: false,
        features: &["exact_integer_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_compound_literal",
        federated: false,
        features: &["compound_get_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
    MatrixRow {
        id: "lang_compound_bound",
        federated: false,
        features: &["compound_get_identity", "entity_get", "dry_live_parity"],
        min_node_results: 1,
        expect_markdown_substrings: &["```tsv"],
        expect_live_error: None,
    },
];
