// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::{BamlDecode, __internal::serde::Serialize};
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainCapability {



    pub name: Option<String>,



    pub kind: Option<types::CapabilityKind>,



    pub description: Option<String>,



    pub http_method: Option<String>,



    pub path_template: Option<String>,



    pub parameters: Vec<DomainParameter>,



    pub request_body_fields: Vec<DomainField>,



    pub response_entity: Option<String>,



    pub response_is_array: Option<bool>,


}



impl ::std::convert::AsRef<DomainCapability> for DomainCapability {
    fn as_ref(&self) -> &DomainCapability {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainEntity {



    pub name: Option<String>,



    pub description: Option<String>,



    pub id_field: Option<String>,



    pub id_type: Option<types::FieldType>,



    pub alternate_keys: Vec<String>,



    pub fields: Vec<DomainField>,



    pub relations: Vec<DomainRelation>,



    pub capabilities: Vec<DomainCapability>,


}



impl ::std::convert::AsRef<DomainEntity> for DomainEntity {
    fn as_ref(&self) -> &DomainEntity {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainField {



    pub name: Option<String>,



    pub field_type: Option<types::FieldType>,



    pub required: Option<bool>,



    pub description: Option<String>,



    pub shared_type_name: Option<String>,



    pub array_element_type: Option<types::FieldType>,



    pub ref_target_entity: Option<String>,


}



impl ::std::convert::AsRef<DomainField> for DomainField {
    fn as_ref(&self) -> &DomainField {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModel {



    pub entities: Vec<DomainEntity>,



    pub shared_types: Vec<SharedType>,


}



impl ::std::convert::AsRef<DomainModel> for DomainModel {
    fn as_ref(&self) -> &DomainModel {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainModelValidation {



    pub overall_quality: Option<String>,



    pub issues: Vec<ValidationIssue>,



    pub suggestions: Vec<String>,


}



impl ::std::convert::AsRef<DomainModelValidation> for DomainModelValidation {
    fn as_ref(&self) -> &DomainModelValidation {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainParameter {



    pub name: Option<String>,



    pub location: Option<types::ParamLocation>,



    pub field_type: Option<types::FieldType>,



    pub required: Option<bool>,



    pub shared_type_name: Option<String>,



    pub description: Option<String>,



    pub ref_target_entity: Option<String>,


}



impl ::std::convert::AsRef<DomainParameter> for DomainParameter {
    fn as_ref(&self) -> &DomainParameter {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct DomainRelation {



    pub name: Option<String>,



    pub target_entity: Option<String>,



    pub cardinality: Option<types::Cardinality>,



    pub foreign_key_field: Option<String>,



    pub evidence: Option<String>,


}



impl ::std::convert::AsRef<DomainRelation> for DomainRelation {
    fn as_ref(&self) -> &DomainRelation {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct PlanChatTurn {



    pub role: Option<types::Union2KassistantOrKuser>,



    pub content: Option<String>,


}



impl ::std::convert::AsRef<PlanChatTurn> for PlanChatTurn {
    fn as_ref(&self) -> &PlanChatTurn {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct PlasmPlan {



    pub text: Option<String>,



    pub reasoning: Option<String>,


}



impl ::std::convert::AsRef<PlasmPlan> for PlasmPlan {
    fn as_ref(&self) -> &PlasmPlan {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SharedType {



    pub name: Option<String>,



    pub description: Option<String>,



    pub values: Vec<String>,



    pub used_by: Vec<String>,


}



impl ::std::convert::AsRef<SharedType> for SharedType {
    fn as_ref(&self) -> &SharedType {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct ValidationIssue {



    pub severity: Option<String>,



    pub entity: Option<String>,



    pub description: Option<String>,


}



impl ::std::convert::AsRef<ValidationIssue> for ValidationIssue {
    fn as_ref(&self) -> &ValidationIssue {
        self
    }
}

