//! MCP App plan review resource bytes (`ui://plasm/plan-review`).

pub const PLAN_REVIEW_UI_URI: &str = "ui://plasm/plan-review";
pub const PLAN_REVIEW_UI_MIME: &str = "text/html;profile=mcp-app";

/// Bundled iframe shell (generated by `scripts/ci/ensure-plan-ui-bundle.sh`).
pub static PLAN_REVIEW_UI_HTML: &str = include_str!("assets/plan_ui.html");

/// HTTP iframe page (`GET /v1/plan/ui/app`) — external script to avoid inline `</script>` leaks.
pub static PLAN_UI_PAGE_HTML: &str = include_str!("assets/plan_ui_page.html");

/// JS module for [`PLAN_UI_PAGE_HTML`] (`GET /v1/plan/ui/app.js`).
pub static PLAN_UI_JS: &str = include_str!("assets/plan_ui.js");

/// Bundled AppBridge host shell (served at `GET /v1/plan/ui` on the appliance).
pub static PLAN_SHELL_HTML: &str = include_str!("assets/plan_shell.html");

/// JS module for [`PLAN_SHELL_HTML`] (`GET /v1/plan/ui/shell.js`).
pub static PLAN_SHELL_JS: &str = include_str!("assets/plan_shell.js");

pub fn plan_review_ui_tool_meta() -> serde_json::Map<String, serde_json::Value> {
    serde_json::json!({
        "ui": {
            "resourceUri": PLAN_REVIEW_UI_URI
        }
    })
    .as_object()
    .cloned()
    .expect("plan review ui meta object")
}

