//! MCP App run explorer resource bytes (`ui://plasm/run-explorer`).

pub const RUN_EXPLORER_UI_URI: &str = "ui://plasm/run-explorer";
pub const RUN_EXPLORER_UI_MIME: &str = "text/html;profile=mcp-app";

/// Bundled iframe shell (generated by `scripts/ci/ensure-run-ui-bundle.sh`).
pub static RUN_EXPLORER_UI_HTML: &str = include_str!("assets/run_ui.html");

/// HTTP iframe page (`GET /v1/run/ui/app`) — external script to avoid inline `</script>` leaks.
pub static RUN_UI_PAGE_HTML: &str = include_str!("assets/run_ui_page.html");

/// JS module for [`RUN_UI_PAGE_HTML`] (`GET /v1/run/ui/app.js`).
pub static RUN_UI_JS: &str = include_str!("assets/run_ui.js");

/// Bundled AppBridge host shell (served at `GET /v1/run/ui` on the appliance).
pub static RUN_SHELL_HTML: &str = include_str!("assets/run_shell.html");

/// JS module for [`RUN_SHELL_HTML`] (`GET /v1/run/ui/shell.js`).
pub static RUN_SHELL_JS: &str = include_str!("assets/run_shell.js");

pub fn run_explorer_ui_tool_meta() -> serde_json::Map<String, serde_json::Value> {
    serde_json::json!({
        "ui": {
            "resourceUri": RUN_EXPLORER_UI_URI
        }
    })
    .as_object()
    .cloned()
    .expect("run explorer ui meta object")
}

