//! Filesystem mirrors for the remote terminal; server sessions own symbols and pins.
use anyhow::Result;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExecutionBinding {
    pub prompt_hash: String,
    pub session: String,
}

pub fn workspace_dir() -> PathBuf {
    std::env::var_os("PLASM_WORKSPACE")
        .map(PathBuf::from)
        .or_else(|| std::env::current_dir().ok())
        .unwrap_or_else(|| PathBuf::from("."))
}

/// Project-local Plasm CLI state root (`.plasm/` under [`workspace_dir`]).
pub fn plasm_root_dir() -> PathBuf {
    workspace_dir().join(".plasm")
}

pub fn profile_path(profile_name: &str) -> PathBuf {
    plasm_root_dir()
        .join("profiles")
        .join(format!("{profile_name}.json"))
}

pub fn language_frontmatter_markdown_path() -> PathBuf {
    plasm_root_dir().join("grammar.md")
}

pub fn plasm_cli_agent_skill_path() -> PathBuf {
    plasm_root_dir()
        .join("skills")
        .join("plasm-cli")
        .join("SKILL.md")
}

pub fn host_slug(server: &str) -> String {
    let h = Sha256::digest(server.as_bytes());
    hex::encode(h)[..8].to_string()
}

pub fn host_mirror_dir(server: &str) -> PathBuf {
    plasm_root_dir().join("hosts").join(host_slug(server))
}

pub fn current_session_pointer_path(server: &str) -> PathBuf {
    host_mirror_dir(server).join("current")
}

pub fn session_dir(client_session_id: &str) -> PathBuf {
    plasm_root_dir().join("s").join(client_session_id)
}

pub fn symbol_state_path(_server: &str, client_session_id: &str) -> PathBuf {
    session_dir(client_session_id).join("symbols.json")
}

pub fn session_out_dir(client_session_id: &str) -> PathBuf {
    session_dir(client_session_id).join("out")
}

pub fn display_mirror_path(path: &Path) -> String {
    let ws = workspace_dir();
    if let Ok(rel) = path.strip_prefix(&ws) {
        rel.display().to_string()
    } else if let Ok(rel) = path.strip_prefix(plasm_root_dir()) {
        format!(".plasm/{}", rel.display())
    } else {
        path.display().to_string()
    }
}

pub fn mint_client_session_id() -> String {
    hex::encode(Uuid::new_v4().as_bytes())[..8].to_string()
}

pub fn write_current_session_pointer(server: &str, client_session_id: &str) -> Result<PathBuf> {
    let dir = host_mirror_dir(server);
    std::fs::create_dir_all(&dir)?;
    let path = current_session_pointer_path(server);
    std::fs::write(&path, format!("{client_session_id}\n"))?;
    Ok(path)
}

pub fn read_current_session_pointer(server: &str) -> Result<Option<String>> {
    let path = current_session_pointer_path(server);
    if !path.exists() {
        return Ok(None);
    }
    let raw = std::fs::read_to_string(&path)?;
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if let Some(id) = line.strip_prefix("client_session_id ") {
            let id = id.trim();
            if !id.is_empty() {
                return Ok(Some(id.to_string()));
            }
        } else if !line.contains(char::is_whitespace) {
            return Ok(Some(line.to_string()));
        }
    }
    Ok(None)
}

pub fn format_language_frontmatter_markdown(frontmatter: &str) -> String {
    format!(
        "# Plasm Grammar\n\n\
This file is generated by `plasm init` so local agents can read the same \
canonical `plasm` MCP tool description (grammar contract) that production agents \
receive via MCP `tools/list`.\n\n\
```text\n{}\n```\n",
        frontmatter.trim()
    )
}

pub fn write_language_frontmatter_markdown(frontmatter: &str) -> Result<PathBuf> {
    let path = language_frontmatter_markdown_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, format_language_frontmatter_markdown(frontmatter))?;
    Ok(path)
}

pub fn format_plasm_cli_agent_skill(grammar_frontmatter: &str) -> String {
    format!(
        r#"---
name: plasm-cli
description: Operates the remote Plasm HTTP terminal with server-owned routed contexts.
---

# Plasm CLI

1. Run `plasm init` to configure the server and regenerate this guide.
2. Open `plasm context --new --intent "business requirement"`.
3. Read the returned canonical teaching and prerequisite binding guidance.
4. You own conversational choices. Available capabilities do not choose an action
   or authorize execution; ask the user when needed before writing the program.
5. Extend with `plasm context --intent "current need"`, keeping the same session.
6. Submit a program with `plasm run --mode plan`, review it, then use `plasm run`
   with the required review reference. The server parses against its pinned symbols.

`plasm search "intent"` returns a standalone JSON routing receipt. It does not
open or extend execution. Business capabilities, prerequisites, binding edges and
unsupported work remain separate in that receipt.

The active local pointer is `.plasm/hosts/<slug>/current`. Context mirrors under
`.plasm/s/<id>/out/NNNN-context/` contain `routing.json` and `teaching.md`. Read
successive teaching waves; symbols are append-only. `symbols.json` stores the
remote binding and generation, not a client-generated symbol table. Old terminal
state must be replaced with a new routed context after the binary cutover.

Run mirrors contain `program.plasm`, response bodies and available full artifacts.
Use `plasm-repl --schema` for local schema execution.

## Canonical grammar

```text
{grammar}
```
"#,
        grammar = grammar_frontmatter.trim()
    )
}

pub fn write_plasm_cli_agent_skill(grammar_frontmatter: &str) -> Result<PathBuf> {
    let path = plasm_cli_agent_skill_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, format_plasm_cli_agent_skill(grammar_frontmatter))?;
    Ok(path)
}

#[cfg(test)]
pub(crate) mod test_env {
    use std::path::Path;
    use std::sync::{Mutex, MutexGuard};

    static PLASM_WORKSPACE_ENV_TEST_LOCK: Mutex<()> = Mutex::new(());

    pub(crate) fn plasm_workspace_env_lock() -> MutexGuard<'static, ()> {
        PLASM_WORKSPACE_ENV_TEST_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
    }

    /// Serialize tests that mutate `PLASM_WORKSPACE`; restores prior value on drop.
    pub(crate) fn with_plasm_workspace<R>(path: &Path, f: impl FnOnce() -> R) -> R {
        let _guard = plasm_workspace_env_lock();
        let prev = std::env::var_os("PLASM_WORKSPACE");
        std::env::set_var("PLASM_WORKSPACE", path);
        let out = f();
        match prev {
            Some(v) => std::env::set_var("PLASM_WORKSPACE", v),
            None => std::env::remove_var("PLASM_WORKSPACE"),
        }
        out
    }
}
