//! MCP App workflow tools + `ui://plasm/workflow` resource bytes.

use std::collections::BTreeMap;
use std::sync::Arc;

use rust_mcp_sdk::schema::schema_utils::CallToolError;
use rust_mcp_sdk::schema::{
    CallToolResult, TextContent, Tool, ToolAnnotations, ToolExecution, ToolExecutionTaskSupport,
    ToolInputSchema,
};
use rust_mcp_sdk::McpServer;
use serde_json::json;
use tracing::Instrument;

use crate::http_execute::{
    apply_capability_seeds, normalize_capability_seeds, CapabilitySeed, RankedCapabilitiesArg,
};
use crate::incoming_auth::tenant_scope;
use crate::mcp_logical_ref::format_logical_session_wire_ref;
use crate::mcp_server::{
    parse_logical_session_ref_arg, parse_optional_principal, PlasmExecBinding, PlasmMcpHandler,
};
use crate::session_identity::ClientSessionKey;
use crate::workflow_manifest::WorkflowManifest;
use crate::workflow_readiness::assess_workflow_readiness;
use crate::workflow_view_model::{
    build_workflow_view_model_with_readiness, instantiate_workflow_program,
    sym_exposure_from_entity_symbols, sym_exposure_refs,
};

pub const WORKFLOW_UI_URI: &str = "ui://plasm/workflow";
pub const WORKFLOW_UI_MIME: &str = "text/html;profile=mcp-app";

/// Bundled iframe shell (generated by `scripts/ci/ensure-workflow-ui-bundle.sh`).
pub static WORKFLOW_UI_HTML: &str = include_str!("assets/workflow_ui.html");

/// HTTP iframe page (`GET /v1/workflows/ui/app`) — external script to avoid inline `</script>` leaks.
pub static WORKFLOW_UI_PAGE_HTML: &str = include_str!("assets/workflow_ui_page.html");

/// JS module for [`WORKFLOW_UI_PAGE_HTML`] (`GET /v1/workflows/ui/app.js`).
pub static WORKFLOW_UI_JS: &str = include_str!("assets/workflow_ui.js");

/// Bundled AppBridge host shell (served at `GET /v1/workflows/ui` on the appliance).
pub static WORKFLOW_SHELL_HTML: &str = include_str!("assets/workflow_shell.html");

/// JS module for [`WORKFLOW_SHELL_HTML`] (`GET /v1/workflows/ui/shell.js`).
pub static WORKFLOW_SHELL_JS: &str = include_str!("assets/workflow_shell.js");

pub fn workflow_mcp_tools() -> Vec<Tool> {
    let mut open_props = BTreeMap::new();
    open_props.insert(
        "id".into(),
        crate::mcp_server::json_schema_non_empty_string_type(
            "Workflow manifest id (e.g. `dossier_linear`).",
        ),
    );
    open_props.insert(
        "intent".into(),
        crate::mcp_server::json_schema_non_empty_string_type(
            "Stable intent string for federated execute session (same rules as `plasm_context`).",
        ),
    );

    let mut dry_props = BTreeMap::new();
    dry_props.insert(
        "id".into(),
        crate::mcp_server::json_schema_non_empty_string_type("Workflow manifest id."),
    );
    dry_props.insert(
        "logical_session_ref".into(),
        crate::mcp_server::json_schema_string_type("Canonical `l_<token>` from `open_workflow`."),
    );
    dry_props.insert(
        "parameters".into(),
        serde_json::from_value(json!({
            "type": "object",
            "description": "Workflow parameter values keyed by manifest field name.",
            "additionalProperties": true
        }))
        .expect("parameters schema"),
    );

    let mut run_props = BTreeMap::new();
    run_props.insert(
        "logical_session_ref".into(),
        crate::mcp_server::json_schema_string_type(
            "Same `l_<token>` as `open_workflow` / `dry_workflow`.",
        ),
    );
    run_props.insert(
        "program".into(),
        crate::mcp_server::json_schema_string_type("Concrete program from `dry_workflow`."),
    );
    run_props.insert(
        "plan_commit_ref".into(),
        crate::mcp_server::json_schema_string_type("Plan token (`pcN`) from `dry_workflow`."),
    );

    let ui_meta = json!({
        "ui": {
            "resourceUri": WORKFLOW_UI_URI
        }
    })
    .as_object()
    .cloned()
    .expect("ui meta object");

    vec![
        Tool {
            name: "open_workflow".into(),
            title: Some("Open federated workflow session".into()),
            description: Some(
                "MCP App: validate registry pins, open federated execute session from workflow seeds, return view-model + entity symbols.".into(),
            ),
            input_schema: ToolInputSchema::new(
                vec!["id".into(), "intent".into()],
                Some(open_props),
                None,
            ),
            annotations: Some(ToolAnnotations {
                read_only_hint: Some(false),
                open_world_hint: Some(true),
                ..Default::default()
            }),
            execution: Some(ToolExecution {
                task_support: Some(ToolExecutionTaskSupport::Forbidden),
            }),
            icons: vec![],
            meta: Some(ui_meta.clone()),
            output_schema: None,
        },
        Tool {
            name: "dry_workflow".into(),
            title: Some("Instantiate + plan dry-run workflow".into()),
            description: Some(
                "MCP App: instantiate program with session symbol map, run plan-only dry-run; requires `plan_ux_reflection` in `_meta.plasm`.".into(),
            ),
            input_schema: ToolInputSchema::new(
                vec!["id".into(), "logical_session_ref".into()],
                Some(dry_props),
                None,
            ),
            annotations: Some(ToolAnnotations {
                read_only_hint: Some(true),
                open_world_hint: Some(true),
                ..Default::default()
            }),
            execution: Some(ToolExecution {
                task_support: Some(ToolExecutionTaskSupport::Forbidden),
            }),
            icons: vec![],
            meta: Some(ui_meta.clone()),
            output_schema: None,
        },
        Tool {
            name: "run_workflow".into(),
            title: Some("Execute approved workflow plan".into()),
            description: Some(
                "MCP App: live execute after `dry_workflow` review (`plan_commit_ref` required when verdict is review).".into(),
            ),
            input_schema: ToolInputSchema::new(
                vec![
                    "logical_session_ref".into(),
                    "program".into(),
                    "plan_commit_ref".into(),
                ],
                Some(run_props),
                None,
            ),
            annotations: Some(ToolAnnotations {
                read_only_hint: Some(false),
                open_world_hint: Some(true),
                ..Default::default()
            }),
            execution: Some(ToolExecution {
                task_support: Some(ToolExecutionTaskSupport::Forbidden),
            }),
            icons: vec![],
            meta: Some(ui_meta),
            output_schema: None,
        },
    ]
}

impl PlasmMcpHandler {
    pub(crate) async fn handle_mcp_tool_open_workflow(
        &self,
        key: &str,
        runtime: &Arc<dyn McpServer>,
        v: &serde_json::Value,
    ) -> Result<CallToolResult, CallToolError> {
        let tname = "open_workflow";
        let principal_incoming = self.ensure_mcp_principal(key, runtime).await?;
        let id = v
            .get("id")
            .and_then(|x| x.as_str())
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .ok_or_else(|| {
                CallToolError::invalid_arguments(tname, Some("missing or empty `id`".into()))
            })?;
        let intent = v
            .get("intent")
            .and_then(|x| x.as_str())
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .ok_or_else(|| {
                CallToolError::invalid_arguments(tname, Some("missing or empty `intent`".into()))
            })?;
        let Some(manifest) = self.plasm.workflows().get(id) else {
            return Err(CallToolError::from_message(format!(
                "unknown workflow `{id}`"
            )));
        };
        let tcfg = self.tenant_mcp_cfg(runtime).await?;
        let catalog = self.plasm.catalog.snapshot();
        let readiness = assess_workflow_readiness(&manifest, catalog.as_ref(), tcfg.as_deref());
        if !readiness.ready {
            return Err(CallToolError::from_message(format!(
                "workflow not ready: {}",
                readiness.blocking_errors.join("; ")
            )));
        }
        let vm = build_workflow_view_model_with_readiness(
            &manifest,
            Some((catalog.as_ref(), tcfg.as_deref())),
        );
        let scope = tenant_scope(principal_incoming.as_ref());
        let rec = self
            .plasm
            .logical_sessions
            .init_session(&scope, &ClientSessionKey::new(intent))
            .await;
        let logical_session_ref = format_logical_session_wire_ref(rec.logical_session_id);
        let logical_uuid = rec.logical_session_id.as_uuid();
        let seeds = manifest_seeds_to_capability_seeds(&manifest);
        let allowed_ids: Option<Vec<String>> = tcfg.as_ref().map(|cfg| {
            let mut ids: Vec<String> = cfg.allowed_entry_ids.iter().cloned().collect();
            ids.sort();
            ids
        });
        let seeds = crate::http_execute::resolve_capability_seeds(
            seeds,
            catalog.as_ref(),
            allowed_ids.as_deref(),
        )
        .map_err(CallToolError::from_message)?;
        let binding = self.resolve_binding_for_logical(key, logical_uuid).await;
        let principal = parse_optional_principal(v);
        let context_span = crate::spans::mcp_tool_plasm_context(logical_session_ref.as_str());
        let out = apply_capability_seeds(
            self.plasm.as_ref(),
            principal_incoming.as_ref(),
            binding
                .as_ref()
                .map(|b| (b.prompt_hash.as_str(), b.session_id.as_str())),
            seeds,
            principal,
            tcfg.clone(),
            Some(logical_uuid),
            intent,
            RankedCapabilitiesArg::Unspecified,
        )
        .instrument(context_span)
        .await
        .map_err(|msg| CallToolError::new(std::io::Error::other(msg)))?;

        if out.binding_updated {
            let ls_key = logical_uuid.to_string();
            let ls = self.logical_mutex(key, &ls_key).await;
            let mut g = ls.lock().await;
            g.binding = Some(PlasmExecBinding {
                prompt_hash: out.prompt_hash.clone(),
                session_id: out.session_id.clone(),
            });
            drop(g);
            self.plasm
                .logical_execute_bindings
                .insert(
                    logical_uuid,
                    out.prompt_hash.clone(),
                    out.session_id.clone(),
                )
                .await;
        }

        let entity_symbols = self
            .plasm
            .get_execute_session(&out.prompt_hash, &out.session_id)
            .await
            .and_then(|sess| {
                sess.teaching_exposure
                    .as_ref()
                    .map(|ex| ex.symbol_map_arc().exposed_entity_symbol_rows())
            })
            .unwrap_or_default();

        let body = json!({
            "logical_session_ref": logical_session_ref,
            "view_model": vm,
            "entity_symbols": entity_symbols,
            "prompt_hash": out.prompt_hash,
            "session_id": out.session_id,
        });
        let mut meta = serde_json::Map::new();
        meta.insert("plasm".into(), body);
        let mut res = CallToolResult::text_content(vec![TextContent::new(
            format!("Workflow `{id}` opened as `{logical_session_ref}`."),
            None,
            None,
        )]);
        res.meta = Some(meta);
        Ok(res)
    }

    pub(crate) async fn handle_mcp_tool_dry_workflow(
        &self,
        key: &str,
        runtime: &Arc<dyn McpServer>,
        v: &serde_json::Value,
    ) -> Result<CallToolResult, CallToolError> {
        let tname = "dry_workflow";
        let id = v
            .get("id")
            .and_then(|x| x.as_str())
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .ok_or_else(|| {
                CallToolError::invalid_arguments(tname, Some("missing or empty `id`".into()))
            })?;
        let session_ref = parse_logical_session_ref_arg(tname, v)?;
        let logical_uuid = self.resolve_logical_session_ref_to_uuid(tname, &session_ref)?;
        let Some(manifest) = self.plasm.workflows().get(id) else {
            return Err(CallToolError::from_message(format!(
                "unknown workflow `{id}`"
            )));
        };
        let template = manifest
            .parsed_template()
            .map_err(|e| CallToolError::from_message(e.to_string()))?;
        let params_json: BTreeMap<String, serde_json::Value> = v
            .get("parameters")
            .and_then(|p| serde_json::from_value(p.clone()).ok())
            .unwrap_or_default();
        let Some(b) = self.resolve_binding_for_logical(key, logical_uuid).await else {
            return Err(CallToolError::from_message(
                "No execute session: call `open_workflow` first.",
            ));
        };
        let Some(sess) = self
            .plasm
            .sessions
            .get_by_strs(&b.prompt_hash, &b.session_id)
            .await
        else {
            return Err(CallToolError::from_message(
                "Execute session expired: call `open_workflow` again.",
            ));
        };
        let entity_symbols = sess
            .teaching_exposure
            .as_ref()
            .map(|ex| ex.symbol_map_arc().exposed_entity_symbol_rows())
            .unwrap_or_default();
        let exposure_map = sym_exposure_from_entity_symbols(&entity_symbols);
        let refs = sym_exposure_refs(&exposure_map);
        let program = instantiate_workflow_program(&manifest, &template, &params_json, &refs)
            .map_err(|e| CallToolError::from_message(e.to_string()))?;
        let dry_v = json!({
            "logical_session_ref": session_ref,
            "program": program.clone(),
        });
        let mut res = self
            .handle_plasm_mcp_tool(
                key,
                runtime,
                &dry_v,
                "plasm",
                true,
                std::time::Instant::now(),
            )
            .await?;
        if let Some(meta) = res.meta.as_mut() {
            if let Some(plasm) = meta.get_mut("plasm").and_then(|v| v.as_object_mut()) {
                plasm.insert("program".into(), json!(program));
            }
        }
        Ok(res)
    }

    pub(crate) async fn handle_mcp_tool_run_workflow(
        &self,
        key: &str,
        runtime: &Arc<dyn McpServer>,
        v: &serde_json::Value,
    ) -> Result<CallToolResult, CallToolError> {
        self.handle_plasm_mcp_tool(
            key,
            runtime,
            v,
            "plasm_run",
            false,
            std::time::Instant::now(),
        )
        .await
    }
}

fn manifest_seeds_to_capability_seeds(manifest: &WorkflowManifest) -> Vec<CapabilitySeed> {
    normalize_capability_seeds(
        manifest
            .seeds
            .iter()
            .map(|s| CapabilitySeed {
                entry_id: s.entry_id.clone(),
                entity: s.entity.clone(),
            })
            .collect(),
    )
}
